import { config } from 'dotenv'
import path from 'path'

config({ path: path.resolve(__dirname, '../../../../.env.local') })
config({ path: path.resolve(__dirname, '../../../../.env') })

import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { exercises } from '../schema/exercises'

const rawUrl = process.env['DATABASE_URL']
if (!rawUrl) throw new Error('DATABASE_URL required')

const client = postgres(rawUrl, { ssl: 'require', max: 1 })
const db = drizzle(client)

type ExerciseInsert = typeof exercises.$inferInsert

const j = (arr: string[]) => JSON.stringify(arr)

const LIBRARY: Omit<ExerciseInsert, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // ─── PEITO ────────────────────────────────────────────────────────────────
  {
    name: 'Supino reto com barra',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco', 'anilhas']),
    level: 'beginner',
    description: 'Exercício multiarticular para peitoral maior com barra em banco plano.',
    techniqueTips:
      'Mantenha as escápulas retraídas e deprimidas; cotovelos a ~75° do tronco; barra desce até o esterno.',
    contraindications: j(['lesão no ombro', 'síndrome do impacto']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino inclinado com barra',
    muscleGroup: j(['peitoral superior', 'tríceps', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco inclinado', 'anilhas']),
    level: 'beginner',
    description:
      'Variação do supino com banco inclinado a 30–45° para enfatizar o peitoral superior.',
    techniqueTips:
      'Inclinação do banco entre 30° e 45°; escápulas fixas; barra desce à altura da clavícula.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino declinado com barra',
    muscleGroup: j(['peitoral inferior', 'tríceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco declinado', 'anilhas']),
    level: 'intermediate',
    description: 'Supino em banco declinado para ênfase na porção inferior do peitoral.',
    techniqueTips: 'Banco a -15° a -30°; amplitude controlada; não hiperextenda os cotovelos.',
    contraindications: j(['hipertensão arterial grave', 'refluxo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino reto com halteres',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['halteres', 'banco']),
    level: 'beginner',
    description: 'Supino com halteres permite maior amplitude e ativação estabilizadora.',
    techniqueTips:
      'Halteres se encontram no topo sem bater; gire levemente os punhos na subida; controle a descida.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino inclinado com halteres',
    muscleGroup: j(['peitoral superior', 'tríceps', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'beginner',
    description: 'Variação com halteres para o peitoral superior com maior amplitude de movimento.',
    techniqueTips: 'Banco a 30–45°; halteres paralelos na descida; cotovelos não ultrapassam 90°.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crucifixo reto',
    muscleGroup: j(['peitoral', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco']),
    level: 'beginner',
    description: 'Movimento de isolamento para o peitoral com halteres em banco plano.',
    techniqueTips:
      'Leve flexão no cotovelo durante todo o movimento; amplitude controlada; não force o alongamento.',
    contraindications: j(['lesão no ombro', 'lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crucifixo inclinado',
    muscleGroup: j(['peitoral superior', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'intermediate',
    description: 'Crucifixo em banco inclinado para enfatizar o peitoral superior.',
    techniqueTips:
      'Banco a 30°; mantenha leve flexão no cotovelo; arco de movimento amplo mas controlado.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crossover na polia',
    muscleGroup: j(['peitoral', 'ombro anterior']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia dupla']),
    level: 'beginner',
    description: 'Exercício de isolamento para peitoral com polias cruzadas.',
    techniqueTips:
      'Leve inclinação do tronco à frente; movimento em arco; mãos se cruzam levemente no final.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Flexão de braço',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior', 'core']),
    modality: j(['força', 'resistência muscular', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício básico de empurrar com o peso corporal.',
    techniqueTips:
      'Corpo reto do calcanhar à cabeça; cotovelos a ~45° do tronco; toque o peito ao solo.',
    contraindications: j(['lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Flexão diamante',
    muscleGroup: j(['tríceps', 'peitoral', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Flexão com mãos próximas em formato de diamante para ênfase no tríceps.',
    techniqueTips: 'Indicadores e polegares se tocam; cotovelos ficam junto ao tronco na descida.',
    contraindications: j(['lesão no punho', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pec deck (fly na máquina)',
    muscleGroup: j(['peitoral']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina pec deck']),
    level: 'beginner',
    description: 'Isolamento do peitoral na máquina, ideal para iniciantes e finalizadores.',
    techniqueTips: 'Cotovelos levemente fletidos e fixos; escápulas retraídas; feche devagar.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pullover com haltere',
    muscleGroup: j(['peitoral', 'grande dorsal', 'tríceps longo']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere', 'banco']),
    level: 'intermediate',
    description:
      'Exercício que trabalha simultaneamente peitoral e grande dorsal em arco de ombro.',
    techniqueTips:
      'Corpo perpendicular ao banco; quadril livre; não force demais o arco atrás da cabeça.',
    contraindications: j(['lesão no ombro', 'cifose acentuada']),
    source: 'curated',
    isPublic: true,
  },

  // ─── COSTAS ───────────────────────────────────────────────────────────────
  {
    name: 'Puxada frontal com barra larga',
    muscleGroup: j(['grande dorsal', 'bíceps', 'romboides']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['polia alta', 'barra larga']),
    level: 'beginner',
    description: 'Exercício fundamental para desenvolver largura do dorsal.',
    techniqueTips:
      'Pegada pronada um pouco além dos ombros; puxe até a clavícula; não balance o tronco.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Puxada supinada (underhand lat pulldown)',
    muscleGroup: j(['grande dorsal', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'barra']),
    level: 'beginner',
    description: 'Puxada com pegada supinada que aumenta a participação do bíceps.',
    techniqueTips:
      'Pegada supinada na largura dos ombros; puxe até o queixo; cotovelos colados ao corpo.',
    contraindications: j(['lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada curvada com barra',
    muscleGroup: j(['grande dorsal', 'romboides', 'trapézio médio', 'bíceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto fundamental para espessura do dorsal.',
    techniqueTips: 'Tronco a ~45°; barra sobe em direção ao umbigo; escápulas retraem no topo.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada unilateral com haltere',
    muscleGroup: j(['grande dorsal', 'romboides', 'bíceps', 'trapézio']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere', 'banco']),
    level: 'beginner',
    description: 'Remada com suporte no banco, ideal para trabalho unilateral do dorsal.',
    techniqueTips: 'Coluna neutra; puxe o cotovelo para cima e para trás; gire levemente o tronco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Barra fixa pronada (pull-up)',
    muscleGroup: j(['grande dorsal', 'bíceps', 'core']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Um dos melhores exercícios para o dorsal usando o peso corporal.',
    techniqueTips:
      'Pegada pronada além dos ombros; suba até o queixo cruzar a barra; desça de forma controlada.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Barra fixa supinada (chin-up)',
    muscleGroup: j(['grande dorsal', 'bíceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Variação supinada da barra fixa com maior ênfase no bíceps.',
    techniqueTips:
      'Pegada supinada na largura dos ombros; suba controlando o movimento; evite balanço.',
    contraindications: j(['lesão no bíceps', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada australiana (inverted row)',
    muscleGroup: j(['grande dorsal', 'romboides', 'bíceps', 'core']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['barra fixada baixa', 'peso corporal']),
    level: 'beginner',
    description: 'Remada com o peso corporal em barra baixa, ótima alternativa à barra fixa.',
    techniqueTips: 'Corpo rígido; puxe o peito até a barra; cotovelos a ~45°; eleve o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Levantamento terra (deadlift)',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar', 'trapézio', 'quadríceps']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'O maior exercício composto, ativa praticamente toda a cadeia posterior.',
    techniqueTips:
      'Quadril acima dos joelhos; barra rente à canela; empurre o chão, não puxe a barra; coluna neutra.',
    contraindications: j(['hérnia de disco', 'lesão lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Levantamento terra romeno (RDL)',
    muscleGroup: j(['isquiotibiais', 'glúteos', 'lombar']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Variação do deadlift com ênfase nos isquiotibiais e glúteos.',
    techniqueTips:
      'Joelhos levemente flexionados; empurre o quadril para trás; barra desce pela frente das pernas.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hiperextensão lombar',
    muscleGroup: j(['lombar', 'glúteos', 'isquiotibiais']),
    modality: j(['reabilitação', 'hipertrofia']),
    equipment: j(['banco de hiperextensão']),
    level: 'beginner',
    description: 'Exercício de isolamento para a musculatura lombar.',
    techniqueTips:
      'Suba até a linha do corpo; não hiperextenda; mãos atrás da cabeça ou cruzadas no peito.',
    contraindications: j(['hérnia de disco lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada na máquina (seated cable row)',
    muscleGroup: j(['grande dorsal', 'romboides', 'trapézio médio', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia baixa', 'triângulo ou barra']),
    level: 'beginner',
    description: 'Remada sentado na polia baixa, ótimo para espessura do dorsal.',
    techniqueTips: 'Coluna ereta; puxe até o abdômen; retraia as escápulas no final do movimento.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Face pull',
    muscleGroup: j(['deltóide posterior', 'trapézio', 'manguito rotador']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Exercício essencial para saúde do ombro e postura.',
    techniqueTips:
      'Polia na altura da testa; puxe a corda em direção ao rosto; cotovelos para cima no final.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── OMBROS ───────────────────────────────────────────────────────────────
  {
    name: 'Desenvolvimento com barra (overhead press)',
    muscleGroup: j(['deltóide', 'tríceps', 'trapézio']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto fundamental para ombros.',
    techniqueTips: 'Barra desce à altura do queixo; core ativado; não arqueie demais a lombar.',
    contraindications: j(['lesão no ombro', 'síndrome do impacto']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Desenvolvimento com halteres',
    muscleGroup: j(['deltóide', 'tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Desenvolvimento unilateral com halteres para ombros com maior amplitude.',
    techniqueTips:
      'Halteres na altura das orelhas; suba sem bater no topo; cotovelos levemente à frente.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Desenvolvimento Arnold',
    muscleGroup: j(['deltóide anterior', 'deltóide lateral', 'tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'intermediate',
    description: 'Variação com rotação do punho que ativa todas as cabeças do deltóide.',
    techniqueTips:
      'Começa com palmas para dentro, gira para fora ao subir; movimento fluido e controlado.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação lateral com halteres',
    muscleGroup: j(['deltóide lateral']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide lateral para ampliar visualmente os ombros.',
    techniqueTips:
      'Leve flexão no cotovelo; polegar levemente abaixado (como verter líquido); suba até a linha do ombro.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação frontal com halteres',
    muscleGroup: j(['deltóide anterior', 'peitoral superior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide anterior.',
    techniqueTips:
      'Braços levemente semifletidos; suba alternado ou simultâneo até a linha dos olhos.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação posterior com halteres (reverse fly)',
    muscleGroup: j(['deltóide posterior', 'romboides', 'trapézio']),
    modality: j(['hipertrofia', 'postura']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide posterior e musculatura postural.',
    techniqueTips:
      'Tronco inclinado a 45° ou deitado de bruços; leve flexão no cotovelo; suba em arco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Encolhimento de ombros com barra (shrug)',
    muscleGroup: j(['trapézio superior']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'beginner',
    description: 'Isolamento do trapézio superior.',
    techniqueTips:
      'Eleve os ombros em linha reta (não gire); segure 1 segundo no topo; descida controlada.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada alta com barra',
    muscleGroup: j(['trapézio', 'deltóide lateral', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto para trapézio e deltóide lateral.',
    techniqueTips: 'Pegada próxima; cotovelos sobem acima das mãos; barra desce rente ao corpo.',
    contraindications: j(['síndrome do impacto', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },

  // ─── BÍCEPS ───────────────────────────────────────────────────────────────
  {
    name: 'Rosca direta com barra',
    muscleGroup: j(['bíceps', 'braquial']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'anilhas']),
    level: 'beginner',
    description: 'Exercício clássico de isolamento para bíceps.',
    techniqueTips:
      'Cotovelos fixos ao lado do corpo; não balance o tronco; supinação completa no topo.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca alternada com halteres',
    muscleGroup: j(['bíceps', 'braquial', 'braquiorradial']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Rosca unilateral alternada para melhor concentração e controle.',
    techniqueTips: 'Supine o punho ao subir; cotovelo fixo; desça completamente antes de alternar.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca martelo',
    muscleGroup: j(['braquial', 'braquiorradial', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Variação neutra da rosca que enfatiza o braquial e braquiorradial.',
    techniqueTips:
      'Pegada neutra (polegar para cima); cotovelos fixos; pode ser feita simultânea ou alternada.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca concentrada',
    muscleGroup: j(['bíceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Isolamento máximo do bíceps com apoio do cotovelo na coxa.',
    techniqueTips:
      'Cotovelo apoiado na coxa interna; suba até a contração máxima; evite rotação do tronco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca Scott (preacher curl)',
    muscleGroup: j(['bíceps', 'braquial']),
    modality: j(['hipertrofia']),
    equipment: j(['barra EZ', 'banco Scott']),
    level: 'beginner',
    description: 'Rosca no banco inclinado que isola o bíceps eliminando o balanço.',
    techniqueTips:
      'Braços totalmente apoiados; não estenda completamente o cotovelo no fundo para proteger a articulação.',
    contraindications: j(['lesão no cotovelo', 'lesão no tendão do bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca inversa',
    muscleGroup: j(['braquiorradial', 'extensores do punho', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'halteres']),
    level: 'intermediate',
    description: 'Rosca com pegada pronada para fortalecer antebraços e braquiorradial.',
    techniqueTips:
      'Pegada pronada; punhos neutros; cotovelos fixos; movimento mais curto que a rosca convencional.',
    contraindications: j(['lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca inclinada com halteres',
    muscleGroup: j(['bíceps (cabeça longa)', 'braquial']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'intermediate',
    description: 'Banco inclinado cria maior pré-estiramento, focando na cabeça longa do bíceps.',
    techniqueTips: 'Banco a 45°–60°; braços pendurados naturalmente; supine o punho ao subir.',
    contraindications: j(['lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },

  // ─── TRÍCEPS ──────────────────────────────────────────────────────────────
  {
    name: 'Tríceps corda na polia',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Isolamento do tríceps na polia alta com corda.',
    techniqueTips:
      'Cotovelos fixos ao lado do corpo; abra a corda ao final; estenda completamente o cotovelo.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps testa com barra (skull crusher)',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra EZ', 'banco']),
    level: 'intermediate',
    description: 'Exercício de isolamento para tríceps com barra EZ.',
    techniqueTips:
      'Barra desce até a testa ou atrás da cabeça; apenas o antebraço se move; cotovelos apontam para cima.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps francês com haltere (overhead triceps extension)',
    muscleGroup: j(['tríceps (cabeça longa)']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Extensão por cima da cabeça que alonga ao máximo a cabeça longa do tríceps.',
    techniqueTips:
      'Segurar o haltere com as duas mãos; cotovelos apontam para frente; amplitude máxima.',
    contraindications: j(['lesão no cotovelo', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Mergulho em paralelas (dip)',
    muscleGroup: j(['tríceps', 'peitoral', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['paralelas']),
    level: 'intermediate',
    description: 'Exercício composto de peso corporal para tríceps e peitoral.',
    techniqueTips:
      'Tronco vertical enfatiza tríceps; inclinado à frente enfatiza peito; desça até 90° no cotovelo.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps coice com haltere (kickback)',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Isolamento do tríceps com extensão do cotovelo para trás.',
    techniqueTips: 'Tronco paralelo ao chão; braço paralelo ao tronco; apenas o antebraço se move.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Extensão de tríceps unilateral na polia',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'acessório']),
    level: 'beginner',
    description: 'Versão unilateral do tríceps na polia para corrigir assimetrias.',
    techniqueTips: 'Cotovelo fixo; extensão completa no fundo; controle a volta.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── QUADRÍCEPS ───────────────────────────────────────────────────────────
  {
    name: 'Agachamento livre com barra',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'lombar', 'core']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra', 'anilhas', 'rack']),
    level: 'intermediate',
    description: 'O rei dos exercícios para membros inferiores.',
    techniqueTips:
      'Pés na largura dos ombros; joelhos na direção dos dedos; desça abaixo de 90°; coluna neutra.',
    contraindications: j(['lesão no joelho grave', 'hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento frontal (front squat)',
    muscleGroup: j(['quadríceps', 'core', 'glúteos']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas', 'rack']),
    level: 'advanced',
    description: 'Variação do agachamento com barra à frente, ênfase no quadríceps.',
    techniqueTips:
      'Cotovelos altos; tronco mais ereto que no agachamento traseiro; mobilidade de tornozelo é crucial.',
    contraindications: j(['lesão no punho', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento sumô',
    muscleGroup: j(['quadríceps', 'glúteos', 'adutores']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'haltere', 'kettlebell']),
    level: 'beginner',
    description: 'Agachamento com pegada larga que enfatiza adutores e glúteos.',
    techniqueTips:
      'Pés além da largura dos ombros com bicos virados para fora; joelhos seguem os pés.',
    contraindications: j(['lesão no quadril']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Leg press 45°',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['máquina leg press 45°']),
    level: 'beginner',
    description: 'Exercício composto para membros inferiores na máquina inclinada.',
    techniqueTips:
      'Pés na largura dos ombros; não trave os joelhos no topo; desça até 90° ou mais.',
    contraindications: j(['lesão no joelho', 'hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Extensão de pernas na máquina',
    muscleGroup: j(['quadríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina extensora']),
    level: 'beginner',
    description: 'Isolamento do quadríceps na máquina extensora.',
    techniqueTips:
      'Suba até extensão completa; segure 1 segundo; desça de forma controlada; atenção à dor patelar.',
    contraindications: j(['condromalácia patelar', 'lesão no ligamento patelar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hack squat na máquina',
    muscleGroup: j(['quadríceps', 'glúteos']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['máquina hack squat']),
    level: 'beginner',
    description: 'Agachamento na máquina inclinada com segurança estrutural aumentada.',
    techniqueTips:
      'Pés na plataforma com ombros encostados; desça até abaixo de 90°; joelhos na direção dos pés.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Afundo com halteres (lunges)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Exercício unilateral funcional para membros inferiores.',
    techniqueTips:
      'Passo largo; joelho da frente não ultrapassa os dedos; tronco ereto; joelho de trás quase toca o chão.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento búlgaro (split squat elevado)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['halteres', 'banco']),
    level: 'intermediate',
    description: 'Agachamento unilateral com pé traseiro elevado — alta ativação do glúteo.',
    techniqueTips:
      'Pé traseiro no banco; tronco levemente inclinado; pé da frente longe o suficiente para joelho não ultrapassar o dedo.',
    contraindications: j(['lesão no joelho', 'lesão no quadril']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento goblet',
    muscleGroup: j(['quadríceps', 'glúteos', 'core']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['kettlebell', 'haltere']),
    level: 'beginner',
    description: 'Agachamento segurando o peso à frente, ótimo para aprender a mecânica.',
    techniqueTips:
      'Peso seguro na altura do peito; cotovelos dentro dos joelhos na descida; tronco ereto.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento com salto (jump squat)',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha']),
    modality: j(['potência', 'condicionamento']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description:
      'Variação pliométrica do agachamento para desenvolver potência de membros inferiores.',
    techniqueTips:
      'Desça em 2–3s; salte explosivamente; aterrise suave na ponta dos pés, absorvendo o impacto.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },

  // ─── POSTERIOR / GLÚTEOS ──────────────────────────────────────────────────
  {
    name: 'Hip thrust com barra',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'banco', 'anilhas']),
    level: 'intermediate',
    description: 'O exercício mais eficiente para hipertrofia dos glúteos.',
    techniqueTips:
      'Banco na altura da escápula; barra sobre o quadril com proteção; empurre o quadril para cima até extensão completa.',
    contraindications: j(['dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Glute bridge',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar']),
    modality: j(['reabilitação', 'hipertrofia']),
    equipment: j(['peso corporal', 'haltere']),
    level: 'beginner',
    description: 'Elevação de quadril deitado, versão mais acessível do hip thrust.',
    techniqueTips:
      'Pés planos no chão; empurre o calcanhar; esprema os glúteos no topo; coluna neutra.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Stiff com barra (Romanian deadlift)',
    muscleGroup: j(['isquiotibiais', 'glúteos', 'lombar']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício de isolamento para isquiotibiais e glúteos.',
    techniqueTips:
      'Joelhos levemente fletidos; quadril empurra para trás; barra desce pela frente da perna; coluna neutra.',
    contraindications: j(['hérnia de disco', 'lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Cadeira flexora (leg curl deitado)',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina flexora']),
    level: 'beginner',
    description: 'Isolamento dos isquiotibiais na máquina flexora deitada.',
    techniqueTips:
      'Quadril fixo na máquina; suba completamente; desça de forma controlada; não deixe o quadril subir.',
    contraindications: j(['lesão isquiotibial']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Leg curl sentado',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina flexora sentado']),
    level: 'beginner',
    description: 'Variação sentada da flexora que estira mais a cabeça longa do isquiotibial.',
    techniqueTips: 'Coluna ereta; puxe o calcanhar em direção ao glúteo; amplitude máxima.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Coice na polia (cable kickback)',
    muscleGroup: j(['glúteos']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia baixa', 'tornozeleira']),
    level: 'beginner',
    description: 'Isolamento do glúteo com extensão do quadril na polia.',
    techniqueTips: 'Tronco levemente inclinado; glúteo contraído no topo; não balance o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Abdução de quadril na máquina',
    muscleGroup: j(['glúteo médio', 'glúteo mínimo', 'TFL']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['máquina abdutora']),
    level: 'beginner',
    description: 'Isolamento do glúteo médio para estabilidade pélvica.',
    techniqueTips: 'Sente ereto; abra as pernas controladamente; não use impulso.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Step up com halteres',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['halteres', 'caixa ou banco']),
    level: 'beginner',
    description: 'Exercício unilateral funcional simulando subida de escada.',
    techniqueTips:
      'Pé inteiro sobre a caixa; empurre pelo calcanhar; não auxilie com a perna de baixo.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Nórdico (Nordic hamstring curl)',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['força', 'prevenção de lesões']),
    equipment: j(['peso corporal', 'parceiro ou fixador']),
    level: 'advanced',
    description:
      'Um dos melhores exercícios para força excêntrica dos isquiotibiais e prevenção de lesões.',
    techniqueTips:
      'Desça o mais lento possível; use as mãos para frear se necessário; foco na fase excêntrica.',
    contraindications: j(['lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },

  // ─── PANTURRILHA ──────────────────────────────────────────────────────────
  {
    name: 'Panturrilha em pé com barra (calf raise)',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'degrau']),
    level: 'beginner',
    description: 'Exercício de isolamento para panturrilha em posição ereta.',
    techniqueTips:
      'Amplitude completa: calcâneos abaixo do nível do degrau; suba na ponta do pé; segure 1s no topo.',
    contraindications: j(['fascite plantar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha sentado',
    muscleGroup: j(['sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina de panturrilha sentado']),
    level: 'beginner',
    description: 'Panturrilha sentado isola o sóleo (músculo mais profundo).',
    techniqueTips: 'Joelhos a 90°; amplitude máxima; não rebole no fundo.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha no leg press',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina leg press 45°']),
    level: 'beginner',
    description: 'Panturrilha usando a plataforma do leg press para maior carga.',
    techniqueTips: 'Joelhos estendidos; pés na ponta da plataforma; amplitude completa.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha unilateral',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['peso corporal', 'haltere', 'degrau']),
    level: 'beginner',
    description: 'Versão unilateral para corrigir assimetrias e aumentar sobrecarga.',
    techniqueTips: 'Uma perna de cada vez; haltere na mão do mesmo lado; amplitude completa.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── CORE / ABDÔMEN ───────────────────────────────────────────────────────
  {
    name: 'Prancha (plank)',
    muscleGroup: j(['core', 'reto abdominal', 'transverso', 'ombros']),
    modality: j(['resistência muscular', 'funcional', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício isométrico fundamental para estabilidade do core.',
    techniqueTips:
      'Corpo reto do calcanhar à cabeça; não deixe o quadril subir ou cair; respire normalmente.',
    contraindications: j(['dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Prancha lateral',
    muscleGroup: j(['oblíquos', 'quadrado lombar', 'core']),
    modality: j(['resistência muscular', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Variação lateral da prancha para oblíquos e estabilidade lateral.',
    techniqueTips:
      'Cotovelo alinhado com o ombro; quadril elevado; corpo em linha reta; progride para bras estendido.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Abdominal crunch',
    muscleGroup: j(['reto abdominal']),
    modality: j(['hipertrofia', 'resistência muscular']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício clássico de isolamento para o reto abdominal.',
    techniqueTips:
      'Mãos atrás da cabeça sem puxar o pescoço; suba curto e controlado; lombar no chão.',
    contraindications: j(['hérnia de disco cervical', 'dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação de pernas deitado',
    muscleGroup: j(['reto abdominal inferior', 'iliopsoas', 'core']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Exercício para a porção inferior do abdômen.',
    techniqueTips:
      'Lombar pressionada no chão; suba até 90°; desça controlado sem encostar completamente.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Russian twist',
    muscleGroup: j(['oblíquos', 'reto abdominal']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['peso corporal', 'medicine ball', 'haltere']),
    level: 'beginner',
    description: 'Rotação do tronco para trabalhar os oblíquos.',
    techniqueTips:
      'Pés elevados para dificultar; gire o tronco, não só os braços; mantenha o peito aberto.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Dead bug',
    muscleGroup: j(['core', 'transverso', 'multífido']),
    modality: j(['funcional', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício de estabilidade do core com movimentos opostos de braço e perna.',
    techniqueTips:
      'Lombar pressionada no chão durante todo o exercício; movimento lento e controlado.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Mountain climber',
    muscleGroup: j(['core', 'quadríceps', 'ombros']),
    modality: j(['condicionamento', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício dinâmico de core e condicionamento cardiovascular.',
    techniqueTips:
      'Quadril neutro (não deixe subir); joelhos em direção ao peito; ritmo controlado ou explosivo.',
    contraindications: j(['lesão no ombro', 'lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Ab wheel (roda abdominal)',
    muscleGroup: j(['reto abdominal', 'core', 'dorsal', 'ombros']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['roda abdominal']),
    level: 'advanced',
    description: 'Um dos exercícios mais desafiadores para o core.',
    techniqueTips:
      'Comece de joelhos; core contraído; não deixe o quadril cair; volte com o abdômen (não empurrando).',
    contraindications: j(['hérnia de disco', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hollow body hold',
    muscleGroup: j(['core', 'reto abdominal', 'iliopsoas']),
    modality: j(['funcional', 'ginástica']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Posição isométrica de ginástica artística para core rígido.',
    techniqueTips:
      'Lombar completamente no chão; braços e pernas estendidos e elevados; respire normalmente.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Cable crunch (abdominal na polia)',
    muscleGroup: j(['reto abdominal']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Abdominal com sobrecarga usando polia alta, permite progressão de carga.',
    techniqueTips:
      'Joelhos no chão; corda atrás da cabeça; flexione o tronco em direção ao chão; não puxe com os braços.',
    contraindications: j(['hérnia de disco cervical']),
    source: 'curated',
    isPublic: true,
  },

  // ─── FUNCIONAL / KETTLEBELL ───────────────────────────────────────────────
  {
    name: 'Kettlebell swing',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar', 'core', 'ombros']),
    modality: j(['potência', 'condicionamento', 'funcional']),
    equipment: j(['kettlebell']),
    level: 'intermediate',
    description: 'Exercício balístico fundamental do treinamento com kettlebell.',
    techniqueTips:
      'Força vem do quadril (hip hinge), não dos braços; glúteos contraídos no topo; kettlebell flutua.',
    contraindications: j(['hérnia de disco lombar', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Turkish get-up',
    muscleGroup: j(['core', 'ombros', 'quadríceps', 'glúteos']),
    modality: j(['funcional', 'força']),
    equipment: j(['kettlebell', 'haltere']),
    level: 'advanced',
    description: 'Movimento complexo do chão à posição em pé com peso overhead.',
    techniqueTips:
      'Olhe para o peso o tempo todo; movimento lento e deliberado; aprenda sem carga primeiro.',
    contraindications: j(['lesão no ombro', 'problemas de equilíbrio']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Burpee',
    muscleGroup: j(['corpo inteiro', 'peitoral', 'quadríceps', 'core', 'ombros']),
    modality: j(['condicionamento', 'potência', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Exercício de corpo inteiro de alta intensidade.',
    techniqueTips:
      'Desça controlado; flexão completa no solo; salto explosivo com braços acima da cabeça.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Box jump',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'core']),
    modality: j(['potência', 'condicionamento']),
    equipment: j(['caixa pliométrica']),
    level: 'intermediate',
    description: 'Salto sobre caixa para desenvolvimento de potência de membros inferiores.',
    techniqueTips:
      'Salte com os dois pés; aterrise em posição de agachamento suave; desça andando, não saltando.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Thruster',
    muscleGroup: j(['quadríceps', 'glúteos', 'deltóide', 'tríceps', 'core']),
    modality: j(['potência', 'condicionamento', 'funcional']),
    equipment: j(['barra', 'halteres', 'kettlebell']),
    level: 'intermediate',
    description: 'Combinação de agachamento frontal e desenvolvimento overhead.',
    techniqueTips:
      'Use o impulso do agachamento para ajudar no press; extensão completa dos braços no topo.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Farmer walk',
    muscleGroup: j(['trapézio', 'core', 'antebraços', 'glúteos', 'panturrilha']),
    modality: j(['força', 'funcional', 'condicionamento']),
    equipment: j(['halteres', 'kettlebell', 'trap bar']),
    level: 'beginner',
    description: 'Caminhada carregando peso — simples e extremamente eficaz.',
    techniqueTips: 'Postura ereta; ombros para trás; passos curtos e controlados; passo firme.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Battle rope (corda naval)',
    muscleGroup: j(['ombros', 'core', 'antebraços', 'corpo inteiro']),
    modality: j(['condicionamento', 'potência']),
    equipment: j(['corda naval']),
    level: 'beginner',
    description:
      'Exercício de alta intensidade com cordas para condicionamento cardiovascular e força.',
    techniqueTips:
      'Posição atlética com leve flexão nos joelhos; ondas geradas pelos ombros e braços; mantenha o core ativo.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },

  // ─── LEVANTAMENTOS OLÍMPICOS ──────────────────────────────────────────────
  {
    name: 'Power clean',
    muscleGroup: j(['corpo inteiro', 'glúteos', 'isquiotibiais', 'trapézio', 'ombros']),
    modality: j(['potência', 'força', 'olímpico']),
    equipment: j(['barra', 'anilhas']),
    level: 'advanced',
    description: 'Levantamento olímpico de potência para desenvolvimento de explosão.',
    techniqueTips:
      'Sequência: pull da barra, explosão de quadril, encolhimento de ombros, recepção; não dobre a barra.',
    contraindications: j(['lesão no punho', 'lesão no ombro', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Push press',
    muscleGroup: j(['deltóide', 'tríceps', 'quadríceps', 'core']),
    modality: j(['potência', 'força', 'funcional']),
    equipment: j(['barra', 'halteres', 'kettlebell']),
    level: 'intermediate',
    description: 'Desenvolvimento com impulso de pernas para levantamentos mais pesados.',
    techniqueTips:
      'Leve dip de joelhos; use o impulso para iniciar o movimento; trave os braços no topo.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },

  // ─── CARDIO / CONDICIONAMENTO ─────────────────────────────────────────────
  {
    name: 'Corrida na esteira',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'isquiotibiais']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['esteira']),
    level: 'beginner',
    description: 'Cardio clássico em esteira com controle de velocidade e inclinação.',
    techniqueTips:
      'Postura ereta; passada natural; inclina a esteira para aumentar intensidade sem aumentar o impacto.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Bike ergométrica',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['bike ergométrica']),
    level: 'beginner',
    description: 'Cardio de baixo impacto ideal para iniciantes e reabilitação.',
    techniqueTips:
      'Ajuste o banco na altura correta; não deixe o joelho ultrapassar 90° no fundo da pedalada.',
    contraindications: j(['lesão no joelho grave']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remo ergométrico',
    muscleGroup: j(['costas', 'glúteos', 'pernas', 'core', 'braços']),
    modality: j(['cardio', 'condicionamento', 'funcional']),
    equipment: j(['remo ergométrico']),
    level: 'beginner',
    description: 'Cardio de corpo inteiro no remo indoor.',
    techniqueTips:
      'Sequência: pernas primeiro, depois inclinação do tronco, depois braços; na volta é o inverso.',
    contraindications: j(['hérnia de disco', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pular corda',
    muscleGroup: j(['panturrilha', 'ombros', 'core']),
    modality: j(['cardio', 'condicionamento', 'coordenação']),
    equipment: j(['corda de pular']),
    level: 'beginner',
    description: 'Exercício clássico de condicionamento cardiovascular e coordenação.',
    techniqueTips:
      'Pule na ponta dos pés; punhos girando a corda (não os ombros); olhe para frente.',
    contraindications: j(['lesão no tornozelo', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elíptico',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'isquiotibiais', 'braços']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['elíptico']),
    level: 'beginner',
    description: 'Cardio de baixo impacto com movimento elíptico que protege as articulações.',
    techniqueTips: 'Mantenha postura ereta; use os braços ativamente; não se apoie nas alças.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── REABILITAÇÃO / MOBILIDADE ────────────────────────────────────────────
  {
    name: "World's greatest stretch",
    muscleGroup: j(['quadril', 'torácica', 'isquiotibiais', 'ombros']),
    modality: j(['mobilidade', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Sequência de mobilidade que trabalha o corpo todo com um único movimento.',
    techniqueTips:
      'Posição de afundo; mão interna no chão; rotação torácica; mantenha cada posição 2–3s.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hip 90/90',
    muscleGroup: j(['quadril', 'piriforme', 'rotadores do quadril']),
    modality: j(['mobilidade', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício de mobilidade para rotação interna e externa do quadril.',
    techniqueTips: 'Ambas as pernas a 90°; mantenha o peito aberto; troque o lado controladamente.',
    contraindications: j(['lesão no quadril aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Clamshell com elástico',
    muscleGroup: j(['glúteo médio', 'rotadores externos do quadril']),
    modality: j(['reabilitação', 'ativação']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Ativação do glúteo médio, essencial para saúde do joelho e estabilidade pélvica.',
    techniqueTips:
      'Elástico acima dos joelhos; quadril levemente flexionado; abra o joelho como uma concha; não role o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rotação externa de ombro com elástico',
    muscleGroup: j(['manguito rotador', 'infraespinhal', 'redondo menor']),
    modality: j(['reabilitação', 'prevenção']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Exercício essencial para saúde do ombro e prevenção de lesões.',
    techniqueTips:
      'Cotovelo a 90° fixo ao lado do corpo; gire o antebraço para fora; movimento lento e controlado.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Copenhagen plank',
    muscleGroup: j(['adutores', 'core', 'oblíquos']),
    modality: j(['reabilitação', 'força']),
    equipment: j(['banco']),
    level: 'advanced',
    description: 'Prancha lateral com perna no banco — exercício avançado para adutores.',
    techniqueTips:
      'Perna de cima apoiada no banco; elevação pélvica completa; progressão: perna de baixo livre.',
    contraindications: j(['lesão na virilha', 'lesão no adutor']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tibial raise (dorsiflexão)',
    muscleGroup: j(['tibial anterior']),
    modality: j(['reabilitação', 'prevenção']),
    equipment: j(['peso corporal', 'anilha']),
    level: 'beginner',
    description: 'Fortalecimento do tibial anterior para prevenção de canelite.',
    techniqueTips:
      'Calcâneos no chão; levante a ponta do pé; adicione anilha no dorso para progressão.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Single leg deadlift',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'core']),
    modality: j(['funcional', 'reabilitação', 'hipertrofia']),
    equipment: j(['haltere', 'kettlebell', 'peso corporal']),
    level: 'intermediate',
    description: 'Levantamento terra unilateral para equilíbrio e força de cadeia posterior.',
    techniqueTips:
      'Quadril empurra para trás junto com a perna traseira; coluna neutra; olhar para baixo.',
    contraindications: j(['lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Monster walk com elástico',
    muscleGroup: j(['glúteo médio', 'quadríceps', 'adutores']),
    modality: j(['reabilitação', 'ativação']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Caminhada lateral com elástico para ativação do glúteo médio.',
    techniqueTips:
      'Elástico acima dos joelhos; posição de meio agachamento; passos laterais mantendo tensão.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── NATAÇÃO ──────────────────────────────────────────────────────────────
  {
    name: 'Nado crawl — técnica completa',
    muscleGroup: j(['grande dorsal', 'deltóide', 'tríceps', 'quadríceps', 'core']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'beginner',
    description: 'Estilo livre — o mais eficiente para desenvolvimento aeróbico na água.',
    techniqueTips:
      'Rotação de 45° do tronco a cada braçada; rosto sai da água apenas o necessário para inspirar; pernada de 6 tempos por ciclo; mão entra alinhada com o ombro.',
    contraindications: j(['lesão no ombro aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Nado costas — técnica completa',
    muscleGroup: j(['grande dorsal', 'deltóide posterior', 'quadríceps', 'core']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'beginner',
    description:
      'Estilo costas — ideal para quem tem restrição cervical e boa alternativa aeróbica.',
    techniqueTips:
      'Quadris altos na água; rotação de tronco a cada braçada; olhos para o teto; pernada alternada e contínua; entrada da mão além da cabeça com palma para fora.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Nado peito — técnica completa',
    muscleGroup: j(['peitoral', 'adutores', 'deltóide', 'glúteos']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'beginner',
    description: 'Estilo peito — o mais lento, porém excelente para reabilitação e iniciantes.',
    techniqueTips:
      'Braços puxam para dentro antes da respiração; joelhos dobram simultaneamente; pés em "flexão plantar" no chute; deslize após cada ciclo.',
    contraindications: j(['lesão no joelho medial', 'dor patelofemoral']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Nado borboleta — técnica completa',
    muscleGroup: j(['peitoral', 'grande dorsal', 'core', 'glúteos']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'advanced',
    description:
      'Estilo borboleta — o mais exigente tecnicamente; grande demanda de core e ombros.',
    techniqueTips:
      'Dois chutes de perna por braçada; quadris sobem antes dos braços entrarem; entrada das mãos além dos ombros; respiração a cada 2 ou 3 ciclos.',
    contraindications: j(['lesão no ombro', 'lombalgia aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pernada de crawl com prancha',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'core']),
    modality: j(['natação']),
    equipment: j(['piscina', 'prancha de natação']),
    level: 'beginner',
    description: 'Drill isolado de pernada para desenvolver propulsão e posição do corpo.',
    techniqueTips:
      'Segurar a prancha à frente com os braços estendidos; pernada alternada partindo do quadril; tornozelos relaxados; joelhos levemente flexionados.',
    contraindications: j(['lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Braceada de crawl com pullbuoy',
    muscleGroup: j(['grande dorsal', 'deltóide', 'tríceps', 'bíceps']),
    modality: j(['natação']),
    equipment: j(['piscina', 'pullbuoy']),
    level: 'beginner',
    description: 'Drill isolado de braçada com pullbuoy entre as pernas para focar nos braços.',
    techniqueTips:
      'Pullbuoy entre as coxas; braços puxam em alta; cotovelo alto na fase puxada; mão sai na altura do quadril.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Respiração bilateral no crawl',
    muscleGroup: j(['core', 'cervical']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'intermediate',
    description: 'Drill para desenvolver respiração a cada 3 braçadas (ambos os lados).',
    techniqueTips:
      'Inspire apenas quando o rosto sair da água; expire continuamente submerso; boca e nariz expiram simultaneamente; gire o tronco, não só a cabeça.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Sprint de natação (25–50m)',
    muscleGroup: j(['corpo inteiro']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'intermediate',
    description: 'Série de sprints curtos em máxima intensidade para potência e velocidade.',
    techniqueTips:
      'Saída em bloco ou de dentro da água; manter técnica mesmo em alta velocidade; recuperação completa entre repetições (2–4×o tempo do sprint).',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Natação aeróbica contínua',
    muscleGroup: j(['corpo inteiro', 'cardiovascular']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'beginner',
    description: 'Rodagem de 1.000–3.000 m em ritmo confortável (zona 2) para base aeróbica.',
    techniqueTips:
      'Ritmo conversacional — deve conseguir manter a técnica; use cronômetro e controle os tempos por 100 m para monitorar o pace.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Treino intervalado na piscina',
    muscleGroup: j(['corpo inteiro', 'cardiovascular']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'intermediate',
    description: 'Séries de 100–400 m com intervalo controlado para desenvolvimento de limiar.',
    techniqueTips:
      'Ex: 8×100 m com saída a cada 2 min; controle o tempo de cada 100 m; manter ritmo estável nas séries; intervalo decresce conforme condicionamento evolui.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Virada cromada (flip turn)',
    muscleGroup: j(['core', 'quadríceps', 'cardiovascular']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'intermediate',
    description: 'Técnica de virada no crawl para manter velocidade na parede.',
    techniqueTips:
      'Comece a girar a 1 m da parede; rolamento frontal com os pés tocando a parede simultaneamente; empurre forte com as pernas e deslize antes de retomar a pernada.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Exercício de equilíbrio na água (sculling)',
    muscleGroup: j(['antebraços', 'deltóide', 'core']),
    modality: j(['natação']),
    equipment: j(['piscina']),
    level: 'beginner',
    description: 'Movimentos de "oito" com as mãos para desenvolver sensação de água e equilíbrio.',
    techniqueTips:
      'Mãos se movem em figura de 8 pequena; palma ligeiramente inclinada; mantém o corpo estável; pode ser feito em flutuação horizontal ou vertical.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── CORRIDA ──────────────────────────────────────────────────────────────
  {
    name: 'Corrida contínua em zona 2 (rodagem)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'beginner',
    description:
      'Corrida contínua em intensidade baixa-moderada (zona 2) para construção aeróbica.',
    techniqueTips:
      'Frequência cardíaca entre 60–70% da FC máx; deve conseguir conversar frases completas; pace confortável; duração de 30–90 min conforme nível.',
    contraindications: j(['lesão no joelho aguda', 'canelite aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Corrida de limiar (tempo run)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'intermediate',
    description:
      'Corrida em pace de limiar anaeróbico (zona 4) por 20–40 min para elevar o limiar.',
    techniqueTips:
      'Intensidade de 80–90% da FC máx; "confortavelmente difícil" — difícil falar frases; mantenha o pace uniforme; warm-up e cool-down de 10 min.',
    contraindications: j(['lesão no joelho', 'problema cardíaco não avaliado']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Intervalado 400 m',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida', 'pista ou GPS']),
    level: 'intermediate',
    description: 'Repetições de 400 m em pace de 5 km para desenvolvimento de VO2 máx.',
    techniqueTips:
      'Ex: 6–10 × 400 m com intervalo de 90 s a 2 min de caminhada; pace deve ser sustentável — não esprinte; recuperação ativa (caminhar, não parar).',
    contraindications: j(['lesão muscular aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Fartlek',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'beginner',
    description: 'Jogo de velocidades — alternância livre entre ritmos durante a corrida.',
    techniqueTips:
      'Ex: 30 s rápido / 90 s lento por 20–40 min; pode usar referências visuais (acelere até a próxima árvore); informal e divertido, ótimo para quem começa o treino intervalado.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Long run (corrida longa)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'intermediate',
    description: 'Corrida longa semanal em zona 2 para desenvolver base aeróbica e resistência.',
    techniqueTips:
      'Pace lento — deve poder conversar; hidratação a cada 20 min; aumento de 10% de volume por semana; aceite que o pace vai cair no final — é normal.',
    contraindications: j(['lesão no joelho', 'fasciíte plantar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Strides (acelerações progressivas)',
    muscleGroup: j(['quadríceps', 'isquiotibiais', 'panturrilha', 'glúteos']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'beginner',
    description: 'Acelerações de 80–100 m que melhoram a mecânica da passada e a velocidade.',
    techniqueTips:
      'Acelere gradualmente até 90% do máximo nos primeiros 40 m; mantenha 20 m; desacelere suavemente; recuperação completa (90 s) entre strides; geralmente 4–6 strides ao final de um treino leve.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Subidas repetidas (hill repeats)',
    muscleGroup: j(['glúteos', 'quadríceps', 'panturrilha', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida', 'subida de 6–10%']),
    level: 'intermediate',
    description: 'Corridas em subida para força específica e potência de corrida.',
    techniqueTips:
      'Ex: 8–12 × 60–90 s em esforço forte subindo; desça trotando; incline o tronco ligeiramente à frente; passada mais curta que no plano; braços trabalham ativamente.',
    contraindications: j(['lesão no tendão de Aquiles', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Skipping (corrida técnica — joelhos altos)',
    muscleGroup: j(['quadríceps', 'iliopsoas', 'panturrilha', 'core']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'beginner',
    description: 'Drills de técnica com elevação exagerada do joelho para melhorar a mecânica.',
    techniqueTips:
      'Joelho sobe até a horizontal; pé de apoio na ponta; braços em 90°; ritmo controlado; execute em 20–30 m; varie: A-skip, B-skip, C-skip.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Butt kick (corrida técnica — calcanhar glúteo)',
    muscleGroup: j(['isquiotibiais', 'panturrilha']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'beginner',
    description: 'Drill de técnica com talão tocando o glúteo para ativar a fase de recuperação.',
    techniqueTips:
      'Calcanhar sobe ativamente em direção ao glúteo; joelhos apontam para baixo; tronco ereto; braços ritmados; evite inclinar o corpo à frente.',
    contraindications: j(['lesão nos isquiotibiais']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Corrida em trail (off-road)',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'tornozelo', 'cardiovascular']),
    modality: j(['corrida']),
    equipment: j(['tênis de trail']),
    level: 'intermediate',
    description: 'Corrida em terreno irregular — trilha, terra, pedras — com foco em adaptação.',
    techniqueTips:
      'Passos mais curtos que na estrada; olhe 3–5 m à frente; suba andando quando necessário; poste os braços mais afastados para equilíbrio; pace mais lento que no asfalto é normal.',
    contraindications: j(['lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Sprint máximo (60–100 m)',
    muscleGroup: j(['quadríceps', 'isquiotibiais', 'glúteos', 'panturrilha']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida', 'pista']),
    level: 'intermediate',
    description:
      'Sprint em máxima velocidade para desenvolvimento de potência e velocidade máxima.',
    techniqueTips:
      'Aceleração nos primeiros 30 m; tronco se ergue à medida que atinge a velocidade máxima; joelhos altos; braços em 90° com ação enérgica; recuperação de 3–5 min entre repetições.',
    contraindications: j(['lesão muscular aguda', 'isquiotibial grau 2+']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Corrida com variação de pace (progression run)',
    muscleGroup: j(['cardiovascular', 'corpo inteiro']),
    modality: j(['corrida']),
    equipment: j(['tênis de corrida']),
    level: 'intermediate',
    description: 'Corrida que inicia lenta e termina nos últimos km em pace de competição.',
    techniqueTips:
      'Ex: 10 km — primeiros 4 km em Z2, próximos 4 km em Z3, últimos 2 km em Z4; aprende a acelerar quando cansado; excelente para maratonistas e corredores de longa distância.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── LUTA ─────────────────────────────────────────────────────────────────
  {
    name: 'Sombra (shadow boxing)',
    muscleGroup: j(['deltóide', 'core', 'pernas', 'cardiovascular']),
    modality: j(['luta', 'boxe', 'muay thai', 'MMA']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Treino de movimentação e golpes sem oponente — base de qualquer arte marcial.',
    techniqueTips:
      'Mantenha a guarda; movimente os pés constantemente; golpes com intenção mas sem exagero; varie combinações; 3 min de trabalho / 1 min de descanso (rodar de luta).',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Jab-cruzado (1-2)',
    muscleGroup: j(['deltóide anterior', 'peitoral', 'tríceps', 'core', 'glúteos']),
    modality: j(['luta', 'boxe', 'muay thai', 'MMA']),
    equipment: j(['luvas', 'saco ou mitts']),
    level: 'beginner',
    description: 'Combinação básica do boxe — jab da mão da frente + cruzado da mão de trás.',
    techniqueTips:
      'Jab: ombro protege o queixo; cruzado: rotação do quadril e pé traseiro; retorne para a guarda imediatamente; não telegrafie o golpe.',
    contraindications: j(['lesão no punho', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Combinação 3 golpes (1-2-3)',
    muscleGroup: j(['deltóide', 'peitoral', 'core', 'oblíquos']),
    modality: j(['luta', 'boxe', 'muay thai', 'MMA']),
    equipment: j(['luvas', 'saco ou mitts']),
    level: 'intermediate',
    description: 'Jab-cruzado-gancho — introdução ao encadeamento de golpes.',
    techniqueTips:
      'Gancho vem do cotovelo dobrado em 90°; rotação do tronco gera a força; pé da frente gira levemente; mantenha o ritmo, não a força.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Roundhouse kick (chute circular) — muay thai',
    muscleGroup: j(['quadríceps', 'glúteos', 'core', 'isquiotibiais']),
    modality: j(['luta', 'muay thai', 'kickboxing', 'MMA']),
    equipment: j(['luvas', 'caneleira', 'saco']),
    level: 'intermediate',
    description: 'Chute circular com a canela — o golpe mais poderoso do muay thai.',
    techniqueTips:
      'Pivote no pé de apoio; quadril abre completamente; impacto com a parte média da canela; braço do lado do chute desce para equilibrar; não use a ponta do pé.',
    contraindications: j(['lesão no quadril', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Joelhos no clinch — muay thai',
    muscleGroup: j(['quadríceps', 'iliopsoas', 'core', 'ombros']),
    modality: j(['luta', 'muay thai', 'MMA']),
    equipment: j(['luvas', 'protetor bucal', 'parceiro']),
    level: 'intermediate',
    description: 'Golpes de joelho no clinch (abraço) — fundamentais no muay thai.',
    techniqueTips:
      'Controle a nuca do oponente; joelho sobe em direção ao abdômen ou costelas; puxe o adversário ao encontro do joelho; mantenha o equilíbrio no pé de apoio.',
    contraindications: j(['lesão no joelho', 'lesão no quadril']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Sprawl e recuperação de guarda (wrestling)',
    muscleGroup: j(['core', 'glúteos', 'peitoral', 'quadríceps']),
    modality: j(['luta', 'wrestling', 'MMA', 'grappling']),
    equipment: j(['tatame']),
    level: 'intermediate',
    description: 'Defesa de queda — sprawl afasta os quadris e impede a entrada do adversário.',
    techniqueTips:
      'Ao sentir a entrada, dispare os quadris para trás e para baixo; peso no adversário; joelhos longe dele; recupere a posição em pé rapidamente; mãos no chão para equilibrar.',
    contraindications: j(['lesão no ombro', 'lesão lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Guarda fechada (closed guard) — BJJ',
    muscleGroup: j(['adutores', 'core', 'isquiotibiais']),
    modality: j(['luta', 'BJJ', 'grappling', 'MMA']),
    equipment: j(['tatame', 'kimono ou rashguard']),
    level: 'beginner',
    description:
      'Posição de guarda com pernas envolvendo o oponente — posição de controle do chão.',
    techniqueTips:
      'Tornozelos cruzados atrás da cintura do adversário; quadril elevado para trabalho de guarda; controle os braços ou pescoço; não relaxe a tensão das pernas.',
    contraindications: j(['lesão no joelho', 'lesão na virilha']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Armbar (chave de braço) — BJJ',
    muscleGroup: j(['core', 'adutores', 'quadríceps']),
    modality: j(['luta', 'BJJ', 'grappling', 'MMA']),
    equipment: j(['tatame']),
    level: 'intermediate',
    description: 'Finalização sobre o cotovelo — uma das finalizações mais icônicas do BJJ.',
    techniqueTips:
      'Controle o pulso com as duas mãos; peso das coxas sobre o braço; joelhos fechados; eleve o quadril para a pressão; tap imediato ao sentir a pressão.',
    contraindications: j(['lesão no cotovelo', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Estrangulamento triângulo — BJJ',
    muscleGroup: j(['adutores', 'core', 'isquiotibiais']),
    modality: j(['luta', 'BJJ', 'grappling', 'MMA']),
    equipment: j(['tatame']),
    level: 'intermediate',
    description: 'Finalização por estrangulamento usando as pernas em formato de triângulo.',
    techniqueTips:
      'Uma perna sobre a nuca do adversário, a outra encaixada no jarrete; aperte os joelhos; puxe a cabeça para baixo; um braço do oponente fica dentro, o outro fora.',
    contraindications: j(['lesão no quadril', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Passagem de guarda toreando — BJJ',
    muscleGroup: j(['quadríceps', 'core', 'glúteos', 'ombros']),
    modality: j(['luta', 'BJJ', 'grappling']),
    equipment: j(['tatame']),
    level: 'intermediate',
    description: 'Passagem de guarda lateral para a meia guarda ou lado.',
    techniqueTips:
      'Controle os joelhos do adversário; circunde lateralmente; pressione os joelhos para baixo; "corte" o quadril através; estabilize no side control imediatamente.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Saco de pancada — combinações',
    muscleGroup: j(['deltóide', 'peitoral', 'tríceps', 'core', 'cardiovascular']),
    modality: j(['luta', 'boxe', 'muay thai', 'kickboxing', 'MMA']),
    equipment: j(['luvas', 'saco de pancada']),
    level: 'beginner',
    description: 'Treino de combinações de golpes no saco para força, técnica e condicionamento.',
    techniqueTips:
      'Comece lento para fixar a técnica; aumente a intensidade a cada round; varie os golpes; mova os pés constantemente; não fique parado em frente ao saco.',
    contraindications: j(['lesão no punho', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rolamento ofensivo (BJJ drilling)',
    muscleGroup: j(['core', 'ombros', 'corpo inteiro']),
    modality: j(['luta', 'BJJ', 'grappling']),
    equipment: j(['tatame']),
    level: 'beginner',
    description: 'Drilling de movimentos de chão do BJJ — shrimping, bridging, rolamentos.',
    techniqueTips:
      'Shrimp: empurre o chão com o pé e mova o quadril lateralmente; bridge: explosão de quadril para virar; pratique devagar e com perfeição antes de aumentar a velocidade.',
    contraindications: j(['lesão cervical']),
    source: 'curated',
    isPublic: true,
  },

  // ─── CROSSFIT ─────────────────────────────────────────────────────────────
  {
    name: 'Snatch (arranque olímpico)',
    muscleGroup: j(['corpo inteiro', 'glúteos', 'trapézio', 'deltóide', 'quadríceps']),
    modality: j(['crossfit', 'olímpico', 'potência']),
    equipment: j(['barra', 'anilhas']),
    level: 'advanced',
    description: 'Levantamento olímpico que move a barra do chão para acima da cabeça em um tempo.',
    techniqueTips:
      'Fases: first pull (chão aos joelhos), second pull (joelhos ao quadril com explosão), catch (recepção em agachamento aéreo); aprenda com PVC e coach habilitado.',
    contraindications: j(['lesão no ombro', 'lesão no punho', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Clean & jerk (arremesso)',
    muscleGroup: j(['corpo inteiro', 'glúteos', 'deltóide', 'trapézio', 'quadríceps']),
    modality: j(['crossfit', 'olímpico', 'potência']),
    equipment: j(['barra', 'anilhas']),
    level: 'advanced',
    description:
      'Levantamento olímpico em dois tempos: clean (recepção) + jerk (arremesso acima da cabeça).',
    techniqueTips:
      'Clean: mesma mecânica do snatch mas recebe na frente; jerk: dip rápido de joelhos, explosão vertical, split ou power jerk; ombros e punhos devem suportar o recebimento.',
    contraindications: j(['lesão no punho', 'lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Wall ball',
    muscleGroup: j(['quadríceps', 'glúteos', 'deltóide', 'tríceps', 'core']),
    modality: j(['crossfit', 'condicionamento', 'potência']),
    equipment: j(['medicine ball', 'parede']),
    level: 'beginner',
    description: 'Agachamento com arremesso de medicine ball para um alvo na parede (3 m).',
    techniqueTips:
      'Bola na altura do peito ao descer; use o impulso do agachamento para o arremesso; pegue na altura do peito; ritmo constante; respiração controlada.',
    contraindications: j(['lesão no joelho', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Toes to bar (pés à barra)',
    muscleGroup: j(['reto abdominal', 'iliopsoas', 'grande dorsal', 'core']),
    modality: j(['crossfit', 'ginástica', 'condicionamento']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Suspenso na barra, levar os pés até tocá-la em cada repetição.',
    techniqueTips:
      'Pode-se usar o kip (balanço) ou versão strict; kip: balanço com o ombro inicia o movimento; strict: mais difícil, sem balanço; mantenha o controle no retorno.',
    contraindications: j(['lesão no ombro', 'lesão lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Double under (corda dupla)',
    muscleGroup: j(['panturrilha', 'ombros', 'core', 'coordenação']),
    modality: j(['crossfit', 'condicionamento', 'coordenação']),
    equipment: j(['corda de pular speed rope']),
    level: 'intermediate',
    description: 'A corda passa duas vezes por cada salto — exige ritmo, coordenação e explosão.',
    techniqueTips:
      'Salto mais alto que no simples; punhos giram rapidamente (movimento de pulso, não de ombro); pulos na ponta dos pés; pule alto, gire rápido, não o contrário.',
    contraindications: j(['lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rope climb (escalada de corda)',
    muscleGroup: j(['grande dorsal', 'bíceps', 'antebraços', 'core']),
    modality: j(['crossfit', 'funcional', 'força']),
    equipment: j(['corda de escalada']),
    level: 'intermediate',
    description: 'Escalada de corda usando braços e pernas — força de puxada e preensão.',
    techniqueTips:
      'Técnica J-hook nos pés: envolva a corda com o pé e pise no nó formado com o outro pé; puxe com os braços e levante os pés ao mesmo tempo; descida controlada.',
    contraindications: j(['lesão no ombro', 'lesão nas mãos']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Ring dip',
    muscleGroup: j(['tríceps', 'peitoral', 'ombro anterior', 'core']),
    modality: j(['crossfit', 'ginástica', 'força']),
    equipment: j(['argolas']),
    level: 'intermediate',
    description: 'Dip nas argolas — mais instável que nas paralelas, exige maior controle.',
    techniqueTips:
      'Argolas giradas para fora no topo (false grip optional); desce até os ombros abaixo dos cotovelos; suba até extensão completa; ative o core para estabilizar.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'GHD sit-up',
    muscleGroup: j(['reto abdominal', 'iliopsoas', 'quadríceps']),
    modality: j(['crossfit', 'condicionamento']),
    equipment: j(['GHD (Glute-Ham Developer)']),
    level: 'intermediate',
    description: 'Abdominal na máquina GHD com amplitude completa de hiperextensão.',
    techniqueTips:
      'Desce até o paralelo ou além; sobe com os braços em arco para ajudar; não force o movimento — hiperextensão abrupta causa DOMS severo em iniciantes; progrida com poucas repetições.',
    contraindications: j(['hérnia de disco', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Kipping pull-up',
    muscleGroup: j(['grande dorsal', 'bíceps', 'core', 'ombros']),
    modality: j(['crossfit', 'condicionamento']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Pull-up com balanço (kip) para maior volume e velocidade de execução.',
    techniqueTips:
      'Balanço iniciado com ombros (hollow/arch); no momento do arch, puxe e empurre a barra para baixo; não é "trapaça" — é uma técnica específica; exige base de strict pull-ups.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Handstand walk (caminhada invertida)',
    muscleGroup: j(['deltóide', 'tríceps', 'core', 'trapézio']),
    modality: j(['crossfit', 'ginástica']),
    equipment: j(['peso corporal']),
    level: 'advanced',
    description: 'Deslocamento em handstand — exige força de ombro, equilíbrio e coordenação.',
    techniqueTips:
      'Parta do handstand estático; dedo indicador aponta para frente; transfira o peso alternando as mãos em pequenos passos; core rígido; pratique contra a parede primeiro.',
    contraindications: j(['lesão no ombro', 'lesão no punho', 'hipertensão não controlada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Chest to bar pull-up',
    muscleGroup: j(['grande dorsal', 'bíceps', 'romboides']),
    modality: j(['crossfit', 'força']),
    equipment: j(['barra fixa']),
    level: 'advanced',
    description:
      'Pull-up com peito tocando a barra — mais difícil que o queixo à barra convencional.',
    techniqueTips:
      'Pegada um pouco mais larga; peito deve tocar a barra em cada repetição; cotovelos puxam para trás e para baixo; pode usar kip para volume no crossfit.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Amrap 20 min — benchmark crossfit',
    muscleGroup: j(['corpo inteiro', 'cardiovascular']),
    modality: j(['crossfit', 'condicionamento']),
    equipment: j(['peso corporal', 'barra fixa', 'corda']),
    level: 'intermediate',
    description: 'As Many Rounds As Possible (AMRAP) — formato de WOD de 20 min.',
    techniqueTips:
      'Ex: 5 pull-ups, 10 push-ups, 15 air squats (Cindy); ritmo sustentável desde o início; não vá rápido demais nas primeiras rodadas; anote o score para comparar futuramente.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── FISIOTERAPIA ─────────────────────────────────────────────────────────
  {
    name: 'Pêndulo de Codman (ombro)',
    muscleGroup: j(['manguito rotador', 'deltóide', 'cápsula articular do ombro']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['peso leve (0,5–1 kg) opcional']),
    level: 'beginner',
    description: 'Exercício pendular para descompressão e mobilização passiva do ombro.',
    techniqueTips:
      'Incline o tronco com apoio de uma mão; braço pende livremente; faça círculos pequenos no sentido horário e anti-horário; sem força muscular ativa; indicado nas primeiras fases do tratamento de ombro.',
    contraindications: j(['fratura recente do úmero']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Extensão lombar de McKenzie',
    muscleGroup: j(['lombar', 'multífido', 'iliopsoas']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description:
      'Extensão em decúbito ventral para centralização da dor lombar e mobilização discal.',
    techniqueTips:
      'Deite de bruços com as mãos sob os ombros; empurre o tronco para cima mantendo o quadril no chão; suba até o limite da dor; segure 1–2 s; 10 repetições; idealmente 6–8x ao dia nas crises.',
    contraindications: j(['estenose espinhal grave', 'espondilólise']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Flexão lombar de Williams',
    muscleGroup: j(['abdômen', 'glúteos', 'isquiotibiais', 'lombar']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description: 'Série de exercícios de flexão para aliviar compressão facetária lombar.',
    techniqueTips:
      'Inclui: joelho ao peito bilateral, ponte glútea, alongamento de isquiotibiais, e agachamento parcial; ordem é importante; indicado em dores com componente facetário; contraindicado na hérnia de disco aguda.',
    contraindications: j(['hérnia de disco em fase aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Estabilização segmentar lombar',
    muscleGroup: j(['transverso abdominal', 'multífido', 'assoalho pélvico']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description:
      'Ativação dos músculos estabilizadores profundos da coluna — base da reabilitação lombar.',
    techniqueTips:
      'Em decúbito dorsal, contraia levemente o abdômen baixo como se fosse parar de urinar (transverso); mantenha a respiração normal; segure 10 s; 10 repetições; não faça a manobra de Valsalva.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Treino proprioceptivo em prancha de equilíbrio',
    muscleGroup: j(['tornozelo', 'panturrilha', 'tibial anterior', 'perônios', 'core']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['prancha de equilíbrio ou disco proprioceptivo']),
    level: 'beginner',
    description: 'Treino de propriocepção e controle neuromuscular para tornozelo e joelho.',
    techniqueTips:
      'Inicie em apoio bipodal; progrida para unipodal; depois olhos fechados; depois com perturbações externas; 30–60 s por série; essencial pós-entorse de tornozelo.',
    contraindications: j(['entorse aguda (fase inflamatória)']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Controle motor escapular',
    muscleGroup: j(['trapézio inferior', 'serrátil anterior', 'romboides']),
    modality: j(['fisioterapia', 'reabilitação', 'postura']),
    equipment: j(['elástico', 'colchonete']),
    level: 'beginner',
    description: 'Exercícios de repadronização do movimento escapular para síndrome do impacto.',
    techniqueTips:
      'Exercícios em Y, T, W e L com elástico ou no solo; foco em retração e depressão escapular; movimento lento e consciente; sem compensação de tronco; 3×10–15 rep.',
    contraindications: j(['lesão no manguito rotador grau 3+']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Fortalecimento de quadríceps em CCC (mini-agachamento)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['peso corporal', 'elástico opcional']),
    level: 'beginner',
    description:
      'Fortalecimento em cadeia cinética fechada para joelho — menos estresse patelofemoral.',
    techniqueTips:
      'Agachamento de 0° a 60° apenas; joelho alinhado ao segundo dedo do pé; carga progressiva; excelente no pós-cirúrgico de LCA; progrida para agachamento completo conforme tolerância.',
    contraindications: j(['lesão de ligamento aguda sem indicação cirúrgica avaliada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Mobilização neural do nervo mediano',
    muscleGroup: j(['nervo mediano', 'cervical', 'braço']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description:
      'Mobilização neurodinâmica para síndrome do túnel do carpo e cervicalgia com irradiação.',
    techniqueTips:
      'Em decúbito lateral ou em pé; braço abduzido a 90°, cotovelo estendido, punho em dorsiflexão e dedos estendidos; incline a cabeça para o lado oposto; 10–15 repetições lentas; pare se houver piora dos sintomas.',
    contraindications: j(['nervo comprimido em fase aguda com sintomas intensos']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'RPG — postura de fechamento (cadeia posterior)',
    muscleGroup: j(['isquiotibiais', 'paravertebrais', 'panturrilha', 'fáscia plantar']),
    modality: j(['fisioterapia', 'reabilitação', 'postura']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description: 'Postura de Reeducação Postural Global que alonga a cadeia muscular posterior.',
    techniqueTips:
      'Deitado, pernas progressivamente estendidas; coluna em neutro; expiração lenta relaxa a cadeia; correção postural simultânea (não apenas alongamento); sessão com fisioterapeuta habilitado em RPG é ideal.',
    contraindications: j(['lesão aguda isquiotibial']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Treino de equilíbrio unipodal progressivo',
    muscleGroup: j(['tibial anterior', 'perônios', 'gastrocnêmio', 'glúteo médio', 'core']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['peso corporal', 'superfícies instáveis opcionais']),
    level: 'intermediate',
    description: 'Progressão de exercícios de equilíbrio unipodal para reabilitação e prevenção.',
    techniqueTips:
      'Progressão: olhos abertos → olhos fechados → superfície instável → com perturbação; cada fase por 30–60 s; 3 séries por membro; base de qualquer programa de prevenção de queda em idosos.',
    contraindications: j(['fratura não consolidada', 'vertigem intensa']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pompage cervical (tração manual suave)',
    muscleGroup: j(['musculatura cervical profunda', 'trapézio superior']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['colchonete']),
    level: 'beginner',
    description: 'Técnica de descompressão cervical por tração intermitente manual.',
    techniqueTips:
      'Terapeuta segura a cabeça com as duas mãos sob o occipital; tração suave e progressiva; mantém 30 s; libera lentamente; indicado em cervicalgia com ou sem irradiação; nunca force a amplitude.',
    contraindications: j(['instabilidade atlantoaxial', 'fratura cervical', 'tumor cervical']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Reforço excêntrico do tendão patelar (Decline squat)',
    muscleGroup: j(['quadríceps', 'tendão patelar']),
    modality: j(['fisioterapia', 'reabilitação']),
    equipment: j(['rampa de 25° ou prancha inclinada']),
    level: 'intermediate',
    description: 'Protocolo excêntrico de Alfredson adaptado para tendinopatia patelar.',
    techniqueTips:
      'Em rampa declinada de 25°; agachamento unilateral lento (4–6 s na descida); sobe com as duas pernas; 3 × 15 rep; 2x ao dia; pode gerar dor moderada — é esperado no protocolo; reduz em 6–8 semanas.',
    contraindications: j(['tendinite em fase aguda inflamatória intensa']),
    source: 'curated',
    isPublic: true,
  },

  // ─── GINÁSTICA / CALISTENIA ───────────────────────────────────────────────
  {
    name: 'Muscle-up',
    muscleGroup: j(['grande dorsal', 'peitoral', 'tríceps', 'bíceps', 'core']),
    modality: j(['força', 'ginástica', 'funcional']),
    equipment: j(['barra fixa', 'argolas']),
    level: 'advanced',
    description: 'Transição da barra fixa para o dip — exercício de calistenia avançado.',
    techniqueTips:
      'Requer forte base de pull-up e dip; use o swing para iniciantes; kip é técnica válida.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pistol squat (agachamento pistola)',
    muscleGroup: j(['quadríceps', 'glúteos', 'core', 'tornozelo']),
    modality: j(['funcional', 'força', 'ginástica']),
    equipment: j(['peso corporal']),
    level: 'advanced',
    description: 'Agachamento unilateral completo — requer força, equilíbrio e mobilidade.',
    techniqueTips:
      'Perna livre estendida à frente; desça controlado; use suporte para aprender a técnica.',
    contraindications: j(['lesão no joelho', 'mobilidade de tornozelo limitada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Handstand push-up (flexão invertida)',
    muscleGroup: j(['deltóide', 'tríceps', 'trapézio', 'core']),
    modality: j(['força', 'ginástica']),
    equipment: j(['peso corporal', 'parede']),
    level: 'advanced',
    description: 'Desenvolvimento com o peso corporal em posição invertida.',
    techniqueTips: 'Use a parede como apoio; core e glúteos contraídos; desça a cabeça até o chão.',
    contraindications: j(['lesão no ombro', 'hipertensão não controlada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'L-sit',
    muscleGroup: j(['core', 'reto abdominal', 'tríceps', 'iliopsoas']),
    modality: j(['ginástica', 'força']),
    equipment: j(['paralelas', 'peso corporal']),
    level: 'advanced',
    description: 'Posição isométrica de ginástica com corpo em "L".',
    techniqueTips:
      'Braços estendidos; pernas paralelas ao chão; progresso: joelhos dobrados → joelhos estendidos.',
    contraindications: j(['lesão no ombro', 'lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Bear crawl',
    muscleGroup: j(['core', 'ombros', 'quadríceps', 'corpo inteiro']),
    modality: j(['funcional', 'condicionamento']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description:
      'Rastejamento em quatro apoios com joelhos elevados — excelente para core e coordenação.',
    techniqueTips:
      'Joelhos a 2–3 cm do chão; movimentos opostos (mão direita + pé esquerdo); costas retas.',
    contraindications: j(['lesão no punho', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Inchworm',
    muscleGroup: j(['isquiotibiais', 'ombros', 'core']),
    modality: j(['mobilidade', 'funcional', 'aquecimento']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Mobilidade dinâmica que alonga isquiotibiais e ativa o core.',
    techniqueTips:
      'Pernas estendidas ao se curvar; caminhe com as mãos até flexão; opcional: adicione flexão no meio.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
]

async function seed() {
  console.log(`Populando biblioteca de exercícios (${LIBRARY.length} exercícios)...`)

  // Insere em lotes de 25 para não estourar o limite de parâmetros
  const BATCH = 25
  let inserted = 0

  for (let i = 0; i < LIBRARY.length; i += BATCH) {
    const batch = LIBRARY.slice(i, i + BATCH)
    await db.insert(exercises).values(batch).onConflictDoNothing()
    inserted += batch.length
    process.stdout.write(`  ${inserted}/${LIBRARY.length}\n`)
  }

  console.log(`\nSeed concluído — ${inserted} exercícios inseridos.`)
  await client.end()
}

seed().catch((err: unknown) => {
  process.stderr.write(`Seed falhou: ${String(err)}\n`)
  process.exit(1)
})
