import { config } from 'dotenv'
import path from 'path'

config({ path: path.resolve(__dirname, '../../../../.env.local') })
config({ path: path.resolve(__dirname, '../../../../.env') })

import { drizzle } from 'drizzle-orm/postgres-js'
import postgres from 'postgres'
import { exercises } from '../schema/exercises'

const rawUrl = process.env['DATABASE_URL']
if (!rawUrl) throw new Error('DATABASE_URL required')

const client = postgres(rawUrl, { ssl: 'require', max: 1 })
const db = drizzle(client)

type ExerciseInsert = typeof exercises.$inferInsert

const j = (arr: string[]) => JSON.stringify(arr)

const LIBRARY: Omit<ExerciseInsert, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // ─── PEITO ────────────────────────────────────────────────────────────────
  {
    name: 'Supino reto com barra',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco', 'anilhas']),
    level: 'beginner',
    description: 'Exercício multiarticular para peitoral maior com barra em banco plano.',
    techniqueTips:
      'Mantenha as escápulas retraídas e deprimidas; cotovelos a ~75° do tronco; barra desce até o esterno.',
    contraindications: j(['lesão no ombro', 'síndrome do impacto']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino inclinado com barra',
    muscleGroup: j(['peitoral superior', 'tríceps', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco inclinado', 'anilhas']),
    level: 'beginner',
    description:
      'Variação do supino com banco inclinado a 30–45° para enfatizar o peitoral superior.',
    techniqueTips:
      'Inclinação do banco entre 30° e 45°; escápulas fixas; barra desce à altura da clavícula.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino declinado com barra',
    muscleGroup: j(['peitoral inferior', 'tríceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'banco declinado', 'anilhas']),
    level: 'intermediate',
    description: 'Supino em banco declinado para ênfase na porção inferior do peitoral.',
    techniqueTips: 'Banco a -15° a -30°; amplitude controlada; não hiperextenda os cotovelos.',
    contraindications: j(['hipertensão arterial grave', 'refluxo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino reto com halteres',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['halteres', 'banco']),
    level: 'beginner',
    description: 'Supino com halteres permite maior amplitude e ativação estabilizadora.',
    techniqueTips:
      'Halteres se encontram no topo sem bater; gire levemente os punhos na subida; controle a descida.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Supino inclinado com halteres',
    muscleGroup: j(['peitoral superior', 'tríceps', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'beginner',
    description: 'Variação com halteres para o peitoral superior com maior amplitude de movimento.',
    techniqueTips: 'Banco a 30–45°; halteres paralelos na descida; cotovelos não ultrapassam 90°.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crucifixo reto',
    muscleGroup: j(['peitoral', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco']),
    level: 'beginner',
    description: 'Movimento de isolamento para o peitoral com halteres em banco plano.',
    techniqueTips:
      'Leve flexão no cotovelo durante todo o movimento; amplitude controlada; não force o alongamento.',
    contraindications: j(['lesão no ombro', 'lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crucifixo inclinado',
    muscleGroup: j(['peitoral superior', 'ombro anterior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'intermediate',
    description: 'Crucifixo em banco inclinado para enfatizar o peitoral superior.',
    techniqueTips:
      'Banco a 30°; mantenha leve flexão no cotovelo; arco de movimento amplo mas controlado.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Crossover na polia',
    muscleGroup: j(['peitoral', 'ombro anterior']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia dupla']),
    level: 'beginner',
    description: 'Exercício de isolamento para peitoral com polias cruzadas.',
    techniqueTips:
      'Leve inclinação do tronco à frente; movimento em arco; mãos se cruzam levemente no final.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Flexão de braço',
    muscleGroup: j(['peitoral', 'tríceps', 'ombro anterior', 'core']),
    modality: j(['força', 'resistência muscular', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício básico de empurrar com o peso corporal.',
    techniqueTips:
      'Corpo reto do calcanhar à cabeça; cotovelos a ~45° do tronco; toque o peito ao solo.',
    contraindications: j(['lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Flexão diamante',
    muscleGroup: j(['tríceps', 'peitoral', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Flexão com mãos próximas em formato de diamante para ênfase no tríceps.',
    techniqueTips: 'Indicadores e polegares se tocam; cotovelos ficam junto ao tronco na descida.',
    contraindications: j(['lesão no punho', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pec deck (fly na máquina)',
    muscleGroup: j(['peitoral']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina pec deck']),
    level: 'beginner',
    description: 'Isolamento do peitoral na máquina, ideal para iniciantes e finalizadores.',
    techniqueTips: 'Cotovelos levemente fletidos e fixos; escápulas retraídas; feche devagar.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pullover com haltere',
    muscleGroup: j(['peitoral', 'grande dorsal', 'tríceps longo']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere', 'banco']),
    level: 'intermediate',
    description:
      'Exercício que trabalha simultaneamente peitoral e grande dorsal em arco de ombro.',
    techniqueTips:
      'Corpo perpendicular ao banco; quadril livre; não force demais o arco atrás da cabeça.',
    contraindications: j(['lesão no ombro', 'cifose acentuada']),
    source: 'curated',
    isPublic: true,
  },

  // ─── COSTAS ───────────────────────────────────────────────────────────────
  {
    name: 'Puxada frontal com barra larga',
    muscleGroup: j(['grande dorsal', 'bíceps', 'romboides']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['polia alta', 'barra larga']),
    level: 'beginner',
    description: 'Exercício fundamental para desenvolver largura do dorsal.',
    techniqueTips:
      'Pegada pronada um pouco além dos ombros; puxe até a clavícula; não balance o tronco.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Puxada supinada (underhand lat pulldown)',
    muscleGroup: j(['grande dorsal', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'barra']),
    level: 'beginner',
    description: 'Puxada com pegada supinada que aumenta a participação do bíceps.',
    techniqueTips:
      'Pegada supinada na largura dos ombros; puxe até o queixo; cotovelos colados ao corpo.',
    contraindications: j(['lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada curvada com barra',
    muscleGroup: j(['grande dorsal', 'romboides', 'trapézio médio', 'bíceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto fundamental para espessura do dorsal.',
    techniqueTips: 'Tronco a ~45°; barra sobe em direção ao umbigo; escápulas retraem no topo.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada unilateral com haltere',
    muscleGroup: j(['grande dorsal', 'romboides', 'bíceps', 'trapézio']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere', 'banco']),
    level: 'beginner',
    description: 'Remada com suporte no banco, ideal para trabalho unilateral do dorsal.',
    techniqueTips: 'Coluna neutra; puxe o cotovelo para cima e para trás; gire levemente o tronco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Barra fixa pronada (pull-up)',
    muscleGroup: j(['grande dorsal', 'bíceps', 'core']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Um dos melhores exercícios para o dorsal usando o peso corporal.',
    techniqueTips:
      'Pegada pronada além dos ombros; suba até o queixo cruzar a barra; desça de forma controlada.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Barra fixa supinada (chin-up)',
    muscleGroup: j(['grande dorsal', 'bíceps']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra fixa']),
    level: 'intermediate',
    description: 'Variação supinada da barra fixa com maior ênfase no bíceps.',
    techniqueTips:
      'Pegada supinada na largura dos ombros; suba controlando o movimento; evite balanço.',
    contraindications: j(['lesão no bíceps', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada australiana (inverted row)',
    muscleGroup: j(['grande dorsal', 'romboides', 'bíceps', 'core']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['barra fixada baixa', 'peso corporal']),
    level: 'beginner',
    description: 'Remada com o peso corporal em barra baixa, ótima alternativa à barra fixa.',
    techniqueTips: 'Corpo rígido; puxe o peito até a barra; cotovelos a ~45°; eleve o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Levantamento terra (deadlift)',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar', 'trapézio', 'quadríceps']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'O maior exercício composto, ativa praticamente toda a cadeia posterior.',
    techniqueTips:
      'Quadril acima dos joelhos; barra rente à canela; empurre o chão, não puxe a barra; coluna neutra.',
    contraindications: j(['hérnia de disco', 'lesão lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Levantamento terra romeno (RDL)',
    muscleGroup: j(['isquiotibiais', 'glúteos', 'lombar']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Variação do deadlift com ênfase nos isquiotibiais e glúteos.',
    techniqueTips:
      'Joelhos levemente flexionados; empurre o quadril para trás; barra desce pela frente das pernas.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hiperextensão lombar',
    muscleGroup: j(['lombar', 'glúteos', 'isquiotibiais']),
    modality: j(['reabilitação', 'hipertrofia']),
    equipment: j(['banco de hiperextensão']),
    level: 'beginner',
    description: 'Exercício de isolamento para a musculatura lombar.',
    techniqueTips:
      'Suba até a linha do corpo; não hiperextenda; mãos atrás da cabeça ou cruzadas no peito.',
    contraindications: j(['hérnia de disco lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada na máquina (seated cable row)',
    muscleGroup: j(['grande dorsal', 'romboides', 'trapézio médio', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia baixa', 'triângulo ou barra']),
    level: 'beginner',
    description: 'Remada sentado na polia baixa, ótimo para espessura do dorsal.',
    techniqueTips: 'Coluna ereta; puxe até o abdômen; retraia as escápulas no final do movimento.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Face pull',
    muscleGroup: j(['deltóide posterior', 'trapézio', 'manguito rotador']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Exercício essencial para saúde do ombro e postura.',
    techniqueTips:
      'Polia na altura da testa; puxe a corda em direção ao rosto; cotovelos para cima no final.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── OMBROS ───────────────────────────────────────────────────────────────
  {
    name: 'Desenvolvimento com barra (overhead press)',
    muscleGroup: j(['deltóide', 'tríceps', 'trapézio']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto fundamental para ombros.',
    techniqueTips: 'Barra desce à altura do queixo; core ativado; não arqueie demais a lombar.',
    contraindications: j(['lesão no ombro', 'síndrome do impacto']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Desenvolvimento com halteres',
    muscleGroup: j(['deltóide', 'tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Desenvolvimento unilateral com halteres para ombros com maior amplitude.',
    techniqueTips:
      'Halteres na altura das orelhas; suba sem bater no topo; cotovelos levemente à frente.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Desenvolvimento Arnold',
    muscleGroup: j(['deltóide anterior', 'deltóide lateral', 'tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'intermediate',
    description: 'Variação com rotação do punho que ativa todas as cabeças do deltóide.',
    techniqueTips:
      'Começa com palmas para dentro, gira para fora ao subir; movimento fluido e controlado.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação lateral com halteres',
    muscleGroup: j(['deltóide lateral']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide lateral para ampliar visualmente os ombros.',
    techniqueTips:
      'Leve flexão no cotovelo; polegar levemente abaixado (como verter líquido); suba até a linha do ombro.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação frontal com halteres',
    muscleGroup: j(['deltóide anterior', 'peitoral superior']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide anterior.',
    techniqueTips:
      'Braços levemente semifletidos; suba alternado ou simultâneo até a linha dos olhos.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação posterior com halteres (reverse fly)',
    muscleGroup: j(['deltóide posterior', 'romboides', 'trapézio']),
    modality: j(['hipertrofia', 'postura']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Isolamento do deltóide posterior e musculatura postural.',
    techniqueTips:
      'Tronco inclinado a 45° ou deitado de bruços; leve flexão no cotovelo; suba em arco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Encolhimento de ombros com barra (shrug)',
    muscleGroup: j(['trapézio superior']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'beginner',
    description: 'Isolamento do trapézio superior.',
    techniqueTips:
      'Eleve os ombros em linha reta (não gire); segure 1 segundo no topo; descida controlada.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remada alta com barra',
    muscleGroup: j(['trapézio', 'deltóide lateral', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício composto para trapézio e deltóide lateral.',
    techniqueTips: 'Pegada próxima; cotovelos sobem acima das mãos; barra desce rente ao corpo.',
    contraindications: j(['síndrome do impacto', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },

  // ─── BÍCEPS ───────────────────────────────────────────────────────────────
  {
    name: 'Rosca direta com barra',
    muscleGroup: j(['bíceps', 'braquial']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'anilhas']),
    level: 'beginner',
    description: 'Exercício clássico de isolamento para bíceps.',
    techniqueTips:
      'Cotovelos fixos ao lado do corpo; não balance o tronco; supinação completa no topo.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca alternada com halteres',
    muscleGroup: j(['bíceps', 'braquial', 'braquiorradial']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Rosca unilateral alternada para melhor concentração e controle.',
    techniqueTips: 'Supine o punho ao subir; cotovelo fixo; desça completamente antes de alternar.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca martelo',
    muscleGroup: j(['braquial', 'braquiorradial', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Variação neutra da rosca que enfatiza o braquial e braquiorradial.',
    techniqueTips:
      'Pegada neutra (polegar para cima); cotovelos fixos; pode ser feita simultânea ou alternada.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca concentrada',
    muscleGroup: j(['bíceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Isolamento máximo do bíceps com apoio do cotovelo na coxa.',
    techniqueTips:
      'Cotovelo apoiado na coxa interna; suba até a contração máxima; evite rotação do tronco.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca Scott (preacher curl)',
    muscleGroup: j(['bíceps', 'braquial']),
    modality: j(['hipertrofia']),
    equipment: j(['barra EZ', 'banco Scott']),
    level: 'beginner',
    description: 'Rosca no banco inclinado que isola o bíceps eliminando o balanço.',
    techniqueTips:
      'Braços totalmente apoiados; não estenda completamente o cotovelo no fundo para proteger a articulação.',
    contraindications: j(['lesão no cotovelo', 'lesão no tendão do bíceps']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca inversa',
    muscleGroup: j(['braquiorradial', 'extensores do punho', 'bíceps']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'halteres']),
    level: 'intermediate',
    description: 'Rosca com pegada pronada para fortalecer antebraços e braquiorradial.',
    techniqueTips:
      'Pegada pronada; punhos neutros; cotovelos fixos; movimento mais curto que a rosca convencional.',
    contraindications: j(['lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rosca inclinada com halteres',
    muscleGroup: j(['bíceps (cabeça longa)', 'braquial']),
    modality: j(['hipertrofia']),
    equipment: j(['halteres', 'banco inclinado']),
    level: 'intermediate',
    description: 'Banco inclinado cria maior pré-estiramento, focando na cabeça longa do bíceps.',
    techniqueTips: 'Banco a 45°–60°; braços pendurados naturalmente; supine o punho ao subir.',
    contraindications: j(['lesão no bíceps']),
    source: 'curated',
    isPublic: true,
  },

  // ─── TRÍCEPS ──────────────────────────────────────────────────────────────
  {
    name: 'Tríceps corda na polia',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Isolamento do tríceps na polia alta com corda.',
    techniqueTips:
      'Cotovelos fixos ao lado do corpo; abra a corda ao final; estenda completamente o cotovelo.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps testa com barra (skull crusher)',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra EZ', 'banco']),
    level: 'intermediate',
    description: 'Exercício de isolamento para tríceps com barra EZ.',
    techniqueTips:
      'Barra desce até a testa ou atrás da cabeça; apenas o antebraço se move; cotovelos apontam para cima.',
    contraindications: j(['lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps francês com haltere (overhead triceps extension)',
    muscleGroup: j(['tríceps (cabeça longa)']),
    modality: j(['hipertrofia']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Extensão por cima da cabeça que alonga ao máximo a cabeça longa do tríceps.',
    techniqueTips:
      'Segurar o haltere com as duas mãos; cotovelos apontam para frente; amplitude máxima.',
    contraindications: j(['lesão no cotovelo', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Mergulho em paralelas (dip)',
    muscleGroup: j(['tríceps', 'peitoral', 'ombro anterior']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['paralelas']),
    level: 'intermediate',
    description: 'Exercício composto de peso corporal para tríceps e peitoral.',
    techniqueTips:
      'Tronco vertical enfatiza tríceps; inclinado à frente enfatiza peito; desça até 90° no cotovelo.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tríceps coice com haltere (kickback)',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['haltere']),
    level: 'beginner',
    description: 'Isolamento do tríceps com extensão do cotovelo para trás.',
    techniqueTips: 'Tronco paralelo ao chão; braço paralelo ao tronco; apenas o antebraço se move.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Extensão de tríceps unilateral na polia',
    muscleGroup: j(['tríceps']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'acessório']),
    level: 'beginner',
    description: 'Versão unilateral do tríceps na polia para corrigir assimetrias.',
    techniqueTips: 'Cotovelo fixo; extensão completa no fundo; controle a volta.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── QUADRÍCEPS ───────────────────────────────────────────────────────────
  {
    name: 'Agachamento livre com barra',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'lombar', 'core']),
    modality: j(['força', 'hipertrofia', 'funcional']),
    equipment: j(['barra', 'anilhas', 'rack']),
    level: 'intermediate',
    description: 'O rei dos exercícios para membros inferiores.',
    techniqueTips:
      'Pés na largura dos ombros; joelhos na direção dos dedos; desça abaixo de 90°; coluna neutra.',
    contraindications: j(['lesão no joelho grave', 'hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento frontal (front squat)',
    muscleGroup: j(['quadríceps', 'core', 'glúteos']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'anilhas', 'rack']),
    level: 'advanced',
    description: 'Variação do agachamento com barra à frente, ênfase no quadríceps.',
    techniqueTips:
      'Cotovelos altos; tronco mais ereto que no agachamento traseiro; mobilidade de tornozelo é crucial.',
    contraindications: j(['lesão no punho', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento sumô',
    muscleGroup: j(['quadríceps', 'glúteos', 'adutores']),
    modality: j(['força', 'hipertrofia']),
    equipment: j(['barra', 'haltere', 'kettlebell']),
    level: 'beginner',
    description: 'Agachamento com pegada larga que enfatiza adutores e glúteos.',
    techniqueTips:
      'Pés além da largura dos ombros com bicos virados para fora; joelhos seguem os pés.',
    contraindications: j(['lesão no quadril']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Leg press 45°',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['máquina leg press 45°']),
    level: 'beginner',
    description: 'Exercício composto para membros inferiores na máquina inclinada.',
    techniqueTips:
      'Pés na largura dos ombros; não trave os joelhos no topo; desça até 90° ou mais.',
    contraindications: j(['lesão no joelho', 'hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Extensão de pernas na máquina',
    muscleGroup: j(['quadríceps']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina extensora']),
    level: 'beginner',
    description: 'Isolamento do quadríceps na máquina extensora.',
    techniqueTips:
      'Suba até extensão completa; segure 1 segundo; desça de forma controlada; atenção à dor patelar.',
    contraindications: j(['condromalácia patelar', 'lesão no ligamento patelar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hack squat na máquina',
    muscleGroup: j(['quadríceps', 'glúteos']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['máquina hack squat']),
    level: 'beginner',
    description: 'Agachamento na máquina inclinada com segurança estrutural aumentada.',
    techniqueTips:
      'Pés na plataforma com ombros encostados; desça até abaixo de 90°; joelhos na direção dos pés.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Afundo com halteres (lunges)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['halteres']),
    level: 'beginner',
    description: 'Exercício unilateral funcional para membros inferiores.',
    techniqueTips:
      'Passo largo; joelho da frente não ultrapassa os dedos; tronco ereto; joelho de trás quase toca o chão.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento búlgaro (split squat elevado)',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['halteres', 'banco']),
    level: 'intermediate',
    description: 'Agachamento unilateral com pé traseiro elevado — alta ativação do glúteo.',
    techniqueTips:
      'Pé traseiro no banco; tronco levemente inclinado; pé da frente longe o suficiente para joelho não ultrapassar o dedo.',
    contraindications: j(['lesão no joelho', 'lesão no quadril']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento goblet',
    muscleGroup: j(['quadríceps', 'glúteos', 'core']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['kettlebell', 'haltere']),
    level: 'beginner',
    description: 'Agachamento segurando o peso à frente, ótimo para aprender a mecânica.',
    techniqueTips:
      'Peso seguro na altura do peito; cotovelos dentro dos joelhos na descida; tronco ereto.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Agachamento com salto (jump squat)',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha']),
    modality: j(['potência', 'condicionamento']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description:
      'Variação pliométrica do agachamento para desenvolver potência de membros inferiores.',
    techniqueTips:
      'Desça em 2–3s; salte explosivamente; aterrise suave na ponta dos pés, absorvendo o impacto.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },

  // ─── POSTERIOR / GLÚTEOS ──────────────────────────────────────────────────
  {
    name: 'Hip thrust com barra',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar']),
    modality: j(['hipertrofia', 'força']),
    equipment: j(['barra', 'banco', 'anilhas']),
    level: 'intermediate',
    description: 'O exercício mais eficiente para hipertrofia dos glúteos.',
    techniqueTips:
      'Banco na altura da escápula; barra sobre o quadril com proteção; empurre o quadril para cima até extensão completa.',
    contraindications: j(['dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Glute bridge',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar']),
    modality: j(['reabilitação', 'hipertrofia']),
    equipment: j(['peso corporal', 'haltere']),
    level: 'beginner',
    description: 'Elevação de quadril deitado, versão mais acessível do hip thrust.',
    techniqueTips:
      'Pés planos no chão; empurre o calcanhar; esprema os glúteos no topo; coluna neutra.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Stiff com barra (Romanian deadlift)',
    muscleGroup: j(['isquiotibiais', 'glúteos', 'lombar']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'anilhas']),
    level: 'intermediate',
    description: 'Exercício de isolamento para isquiotibiais e glúteos.',
    techniqueTips:
      'Joelhos levemente fletidos; quadril empurra para trás; barra desce pela frente da perna; coluna neutra.',
    contraindications: j(['hérnia de disco', 'lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Cadeira flexora (leg curl deitado)',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['máquina flexora']),
    level: 'beginner',
    description: 'Isolamento dos isquiotibiais na máquina flexora deitada.',
    techniqueTips:
      'Quadril fixo na máquina; suba completamente; desça de forma controlada; não deixe o quadril subir.',
    contraindications: j(['lesão isquiotibial']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Leg curl sentado',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina flexora sentado']),
    level: 'beginner',
    description: 'Variação sentada da flexora que estira mais a cabeça longa do isquiotibial.',
    techniqueTips: 'Coluna ereta; puxe o calcanhar em direção ao glúteo; amplitude máxima.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Coice na polia (cable kickback)',
    muscleGroup: j(['glúteos']),
    modality: j(['hipertrofia', 'definição']),
    equipment: j(['polia baixa', 'tornozeleira']),
    level: 'beginner',
    description: 'Isolamento do glúteo com extensão do quadril na polia.',
    techniqueTips: 'Tronco levemente inclinado; glúteo contraído no topo; não balance o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Abdução de quadril na máquina',
    muscleGroup: j(['glúteo médio', 'glúteo mínimo', 'TFL']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['máquina abdutora']),
    level: 'beginner',
    description: 'Isolamento do glúteo médio para estabilidade pélvica.',
    techniqueTips: 'Sente ereto; abra as pernas controladamente; não use impulso.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Step up com halteres',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais']),
    modality: j(['funcional', 'hipertrofia']),
    equipment: j(['halteres', 'caixa ou banco']),
    level: 'beginner',
    description: 'Exercício unilateral funcional simulando subida de escada.',
    techniqueTips:
      'Pé inteiro sobre a caixa; empurre pelo calcanhar; não auxilie com a perna de baixo.',
    contraindications: j(['lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Nórdico (Nordic hamstring curl)',
    muscleGroup: j(['isquiotibiais']),
    modality: j(['força', 'prevenção de lesões']),
    equipment: j(['peso corporal', 'parceiro ou fixador']),
    level: 'advanced',
    description:
      'Um dos melhores exercícios para força excêntrica dos isquiotibiais e prevenção de lesões.',
    techniqueTips:
      'Desça o mais lento possível; use as mãos para frear se necessário; foco na fase excêntrica.',
    contraindications: j(['lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },

  // ─── PANTURRILHA ──────────────────────────────────────────────────────────
  {
    name: 'Panturrilha em pé com barra (calf raise)',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['barra', 'degrau']),
    level: 'beginner',
    description: 'Exercício de isolamento para panturrilha em posição ereta.',
    techniqueTips:
      'Amplitude completa: calcâneos abaixo do nível do degrau; suba na ponta do pé; segure 1s no topo.',
    contraindications: j(['fascite plantar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha sentado',
    muscleGroup: j(['sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina de panturrilha sentado']),
    level: 'beginner',
    description: 'Panturrilha sentado isola o sóleo (músculo mais profundo).',
    techniqueTips: 'Joelhos a 90°; amplitude máxima; não rebole no fundo.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha no leg press',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia']),
    equipment: j(['máquina leg press 45°']),
    level: 'beginner',
    description: 'Panturrilha usando a plataforma do leg press para maior carga.',
    techniqueTips: 'Joelhos estendidos; pés na ponta da plataforma; amplitude completa.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Panturrilha unilateral',
    muscleGroup: j(['gastrocnêmio', 'sóleo']),
    modality: j(['hipertrofia', 'reabilitação']),
    equipment: j(['peso corporal', 'haltere', 'degrau']),
    level: 'beginner',
    description: 'Versão unilateral para corrigir assimetrias e aumentar sobrecarga.',
    techniqueTips: 'Uma perna de cada vez; haltere na mão do mesmo lado; amplitude completa.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── CORE / ABDÔMEN ───────────────────────────────────────────────────────
  {
    name: 'Prancha (plank)',
    muscleGroup: j(['core', 'reto abdominal', 'transverso', 'ombros']),
    modality: j(['resistência muscular', 'funcional', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício isométrico fundamental para estabilidade do core.',
    techniqueTips:
      'Corpo reto do calcanhar à cabeça; não deixe o quadril subir ou cair; respire normalmente.',
    contraindications: j(['dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Prancha lateral',
    muscleGroup: j(['oblíquos', 'quadrado lombar', 'core']),
    modality: j(['resistência muscular', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Variação lateral da prancha para oblíquos e estabilidade lateral.',
    techniqueTips:
      'Cotovelo alinhado com o ombro; quadril elevado; corpo em linha reta; progride para bras estendido.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Abdominal crunch',
    muscleGroup: j(['reto abdominal']),
    modality: j(['hipertrofia', 'resistência muscular']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício clássico de isolamento para o reto abdominal.',
    techniqueTips:
      'Mãos atrás da cabeça sem puxar o pescoço; suba curto e controlado; lombar no chão.',
    contraindications: j(['hérnia de disco cervical', 'dor lombar aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elevação de pernas deitado',
    muscleGroup: j(['reto abdominal inferior', 'iliopsoas', 'core']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Exercício para a porção inferior do abdômen.',
    techniqueTips:
      'Lombar pressionada no chão; suba até 90°; desça controlado sem encostar completamente.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Russian twist',
    muscleGroup: j(['oblíquos', 'reto abdominal']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['peso corporal', 'medicine ball', 'haltere']),
    level: 'beginner',
    description: 'Rotação do tronco para trabalhar os oblíquos.',
    techniqueTips:
      'Pés elevados para dificultar; gire o tronco, não só os braços; mantenha o peito aberto.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Dead bug',
    muscleGroup: j(['core', 'transverso', 'multífido']),
    modality: j(['funcional', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício de estabilidade do core com movimentos opostos de braço e perna.',
    techniqueTips:
      'Lombar pressionada no chão durante todo o exercício; movimento lento e controlado.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Mountain climber',
    muscleGroup: j(['core', 'quadríceps', 'ombros']),
    modality: j(['condicionamento', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício dinâmico de core e condicionamento cardiovascular.',
    techniqueTips:
      'Quadril neutro (não deixe subir); joelhos em direção ao peito; ritmo controlado ou explosivo.',
    contraindications: j(['lesão no ombro', 'lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Ab wheel (roda abdominal)',
    muscleGroup: j(['reto abdominal', 'core', 'dorsal', 'ombros']),
    modality: j(['hipertrofia', 'funcional']),
    equipment: j(['roda abdominal']),
    level: 'advanced',
    description: 'Um dos exercícios mais desafiadores para o core.',
    techniqueTips:
      'Comece de joelhos; core contraído; não deixe o quadril cair; volte com o abdômen (não empurrando).',
    contraindications: j(['hérnia de disco', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hollow body hold',
    muscleGroup: j(['core', 'reto abdominal', 'iliopsoas']),
    modality: j(['funcional', 'ginástica']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Posição isométrica de ginástica artística para core rígido.',
    techniqueTips:
      'Lombar completamente no chão; braços e pernas estendidos e elevados; respire normalmente.',
    contraindications: j(['hérnia de disco lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Cable crunch (abdominal na polia)',
    muscleGroup: j(['reto abdominal']),
    modality: j(['hipertrofia']),
    equipment: j(['polia alta', 'corda']),
    level: 'beginner',
    description: 'Abdominal com sobrecarga usando polia alta, permite progressão de carga.',
    techniqueTips:
      'Joelhos no chão; corda atrás da cabeça; flexione o tronco em direção ao chão; não puxe com os braços.',
    contraindications: j(['hérnia de disco cervical']),
    source: 'curated',
    isPublic: true,
  },

  // ─── FUNCIONAL / KETTLEBELL ───────────────────────────────────────────────
  {
    name: 'Kettlebell swing',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'lombar', 'core', 'ombros']),
    modality: j(['potência', 'condicionamento', 'funcional']),
    equipment: j(['kettlebell']),
    level: 'intermediate',
    description: 'Exercício balístico fundamental do treinamento com kettlebell.',
    techniqueTips:
      'Força vem do quadril (hip hinge), não dos braços; glúteos contraídos no topo; kettlebell flutua.',
    contraindications: j(['hérnia de disco lombar', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Turkish get-up',
    muscleGroup: j(['core', 'ombros', 'quadríceps', 'glúteos']),
    modality: j(['funcional', 'força']),
    equipment: j(['kettlebell', 'haltere']),
    level: 'advanced',
    description: 'Movimento complexo do chão à posição em pé com peso overhead.',
    techniqueTips:
      'Olhe para o peso o tempo todo; movimento lento e deliberado; aprenda sem carga primeiro.',
    contraindications: j(['lesão no ombro', 'problemas de equilíbrio']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Burpee',
    muscleGroup: j(['corpo inteiro', 'peitoral', 'quadríceps', 'core', 'ombros']),
    modality: j(['condicionamento', 'potência', 'funcional']),
    equipment: j(['peso corporal']),
    level: 'intermediate',
    description: 'Exercício de corpo inteiro de alta intensidade.',
    techniqueTips:
      'Desça controlado; flexão completa no solo; salto explosivo com braços acima da cabeça.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Box jump',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'core']),
    modality: j(['potência', 'condicionamento']),
    equipment: j(['caixa pliométrica']),
    level: 'intermediate',
    description: 'Salto sobre caixa para desenvolvimento de potência de membros inferiores.',
    techniqueTips:
      'Salte com os dois pés; aterrise em posição de agachamento suave; desça andando, não saltando.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Thruster',
    muscleGroup: j(['quadríceps', 'glúteos', 'deltóide', 'tríceps', 'core']),
    modality: j(['potência', 'condicionamento', 'funcional']),
    equipment: j(['barra', 'halteres', 'kettlebell']),
    level: 'intermediate',
    description: 'Combinação de agachamento frontal e desenvolvimento overhead.',
    techniqueTips:
      'Use o impulso do agachamento para ajudar no press; extensão completa dos braços no topo.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Farmer walk',
    muscleGroup: j(['trapézio', 'core', 'antebraços', 'glúteos', 'panturrilha']),
    modality: j(['força', 'funcional', 'condicionamento']),
    equipment: j(['halteres', 'kettlebell', 'trap bar']),
    level: 'beginner',
    description: 'Caminhada carregando peso — simples e extremamente eficaz.',
    techniqueTips: 'Postura ereta; ombros para trás; passos curtos e controlados; passo firme.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Battle rope (corda naval)',
    muscleGroup: j(['ombros', 'core', 'antebraços', 'corpo inteiro']),
    modality: j(['condicionamento', 'potência']),
    equipment: j(['corda naval']),
    level: 'beginner',
    description:
      'Exercício de alta intensidade com cordas para condicionamento cardiovascular e força.',
    techniqueTips:
      'Posição atlética com leve flexão nos joelhos; ondas geradas pelos ombros e braços; mantenha o core ativo.',
    contraindications: j(['lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },

  // ─── LEVANTAMENTOS OLÍMPICOS ──────────────────────────────────────────────
  {
    name: 'Power clean',
    muscleGroup: j(['corpo inteiro', 'glúteos', 'isquiotibiais', 'trapézio', 'ombros']),
    modality: j(['potência', 'força', 'olímpico']),
    equipment: j(['barra', 'anilhas']),
    level: 'advanced',
    description: 'Levantamento olímpico de potência para desenvolvimento de explosão.',
    techniqueTips:
      'Sequência: pull da barra, explosão de quadril, encolhimento de ombros, recepção; não dobre a barra.',
    contraindications: j(['lesão no punho', 'lesão no ombro', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Push press',
    muscleGroup: j(['deltóide', 'tríceps', 'quadríceps', 'core']),
    modality: j(['potência', 'força', 'funcional']),
    equipment: j(['barra', 'halteres', 'kettlebell']),
    level: 'intermediate',
    description: 'Desenvolvimento com impulso de pernas para levantamentos mais pesados.',
    techniqueTips:
      'Leve dip de joelhos; use o impulso para iniciar o movimento; trave os braços no topo.',
    contraindications: j(['lesão no ombro', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },

  // ─── CARDIO / CONDICIONAMENTO ─────────────────────────────────────────────
  {
    name: 'Corrida na esteira',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'isquiotibiais']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['esteira']),
    level: 'beginner',
    description: 'Cardio clássico em esteira com controle de velocidade e inclinação.',
    techniqueTips:
      'Postura ereta; passada natural; inclina a esteira para aumentar intensidade sem aumentar o impacto.',
    contraindications: j(['lesão no joelho', 'lesão no tornozelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Bike ergométrica',
    muscleGroup: j(['quadríceps', 'glúteos', 'isquiotibiais', 'panturrilha']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['bike ergométrica']),
    level: 'beginner',
    description: 'Cardio de baixo impacto ideal para iniciantes e reabilitação.',
    techniqueTips:
      'Ajuste o banco na altura correta; não deixe o joelho ultrapassar 90° no fundo da pedalada.',
    contraindications: j(['lesão no joelho grave']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Remo ergométrico',
    muscleGroup: j(['costas', 'glúteos', 'pernas', 'core', 'braços']),
    modality: j(['cardio', 'condicionamento', 'funcional']),
    equipment: j(['remo ergométrico']),
    level: 'beginner',
    description: 'Cardio de corpo inteiro no remo indoor.',
    techniqueTips:
      'Sequência: pernas primeiro, depois inclinação do tronco, depois braços; na volta é o inverso.',
    contraindications: j(['hérnia de disco', 'lesão lombar']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pular corda',
    muscleGroup: j(['panturrilha', 'ombros', 'core']),
    modality: j(['cardio', 'condicionamento', 'coordenação']),
    equipment: j(['corda de pular']),
    level: 'beginner',
    description: 'Exercício clássico de condicionamento cardiovascular e coordenação.',
    techniqueTips:
      'Pule na ponta dos pés; punhos girando a corda (não os ombros); olhe para frente.',
    contraindications: j(['lesão no tornozelo', 'lesão no joelho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Elíptico',
    muscleGroup: j(['quadríceps', 'glúteos', 'panturrilha', 'isquiotibiais', 'braços']),
    modality: j(['cardio', 'resistência']),
    equipment: j(['elíptico']),
    level: 'beginner',
    description: 'Cardio de baixo impacto com movimento elíptico que protege as articulações.',
    techniqueTips: 'Mantenha postura ereta; use os braços ativamente; não se apoie nas alças.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── REABILITAÇÃO / MOBILIDADE ────────────────────────────────────────────
  {
    name: "World's greatest stretch",
    muscleGroup: j(['quadril', 'torácica', 'isquiotibiais', 'ombros']),
    modality: j(['mobilidade', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Sequência de mobilidade que trabalha o corpo todo com um único movimento.',
    techniqueTips:
      'Posição de afundo; mão interna no chão; rotação torácica; mantenha cada posição 2–3s.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Hip 90/90',
    muscleGroup: j(['quadril', 'piriforme', 'rotadores do quadril']),
    modality: j(['mobilidade', 'reabilitação']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Exercício de mobilidade para rotação interna e externa do quadril.',
    techniqueTips: 'Ambas as pernas a 90°; mantenha o peito aberto; troque o lado controladamente.',
    contraindications: j(['lesão no quadril aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Clamshell com elástico',
    muscleGroup: j(['glúteo médio', 'rotadores externos do quadril']),
    modality: j(['reabilitação', 'ativação']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Ativação do glúteo médio, essencial para saúde do joelho e estabilidade pélvica.',
    techniqueTips:
      'Elástico acima dos joelhos; quadril levemente flexionado; abra o joelho como uma concha; não role o quadril.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Rotação externa de ombro com elástico',
    muscleGroup: j(['manguito rotador', 'infraespinhal', 'redondo menor']),
    modality: j(['reabilitação', 'prevenção']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Exercício essencial para saúde do ombro e prevenção de lesões.',
    techniqueTips:
      'Cotovelo a 90° fixo ao lado do corpo; gire o antebraço para fora; movimento lento e controlado.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Copenhagen plank',
    muscleGroup: j(['adutores', 'core', 'oblíquos']),
    modality: j(['reabilitação', 'força']),
    equipment: j(['banco']),
    level: 'advanced',
    description: 'Prancha lateral com perna no banco — exercício avançado para adutores.',
    techniqueTips:
      'Perna de cima apoiada no banco; elevação pélvica completa; progressão: perna de baixo livre.',
    contraindications: j(['lesão na virilha', 'lesão no adutor']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Tibial raise (dorsiflexão)',
    muscleGroup: j(['tibial anterior']),
    modality: j(['reabilitação', 'prevenção']),
    equipment: j(['peso corporal', 'anilha']),
    level: 'beginner',
    description: 'Fortalecimento do tibial anterior para prevenção de canelite.',
    techniqueTips:
      'Calcâneos no chão; levante a ponta do pé; adicione anilha no dorso para progressão.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Single leg deadlift',
    muscleGroup: j(['glúteos', 'isquiotibiais', 'core']),
    modality: j(['funcional', 'reabilitação', 'hipertrofia']),
    equipment: j(['haltere', 'kettlebell', 'peso corporal']),
    level: 'intermediate',
    description: 'Levantamento terra unilateral para equilíbrio e força de cadeia posterior.',
    techniqueTips:
      'Quadril empurra para trás junto com a perna traseira; coluna neutra; olhar para baixo.',
    contraindications: j(['lesão isquiotibial aguda']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Monster walk com elástico',
    muscleGroup: j(['glúteo médio', 'quadríceps', 'adutores']),
    modality: j(['reabilitação', 'ativação']),
    equipment: j(['elástico']),
    level: 'beginner',
    description: 'Caminhada lateral com elástico para ativação do glúteo médio.',
    techniqueTips:
      'Elástico acima dos joelhos; posição de meio agachamento; passos laterais mantendo tensão.',
    contraindications: j([]),
    source: 'curated',
    isPublic: true,
  },

  // ─── GINÁSTICA / CALISTENIA ───────────────────────────────────────────────
  {
    name: 'Muscle-up',
    muscleGroup: j(['grande dorsal', 'peitoral', 'tríceps', 'bíceps', 'core']),
    modality: j(['força', 'ginástica', 'funcional']),
    equipment: j(['barra fixa', 'argolas']),
    level: 'advanced',
    description: 'Transição da barra fixa para o dip — exercício de calistenia avançado.',
    techniqueTips:
      'Requer forte base de pull-up e dip; use o swing para iniciantes; kip é técnica válida.',
    contraindications: j(['lesão no ombro', 'lesão no cotovelo']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Pistol squat (agachamento pistola)',
    muscleGroup: j(['quadríceps', 'glúteos', 'core', 'tornozelo']),
    modality: j(['funcional', 'força', 'ginástica']),
    equipment: j(['peso corporal']),
    level: 'advanced',
    description: 'Agachamento unilateral completo — requer força, equilíbrio e mobilidade.',
    techniqueTips:
      'Perna livre estendida à frente; desça controlado; use suporte para aprender a técnica.',
    contraindications: j(['lesão no joelho', 'mobilidade de tornozelo limitada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Handstand push-up (flexão invertida)',
    muscleGroup: j(['deltóide', 'tríceps', 'trapézio', 'core']),
    modality: j(['força', 'ginástica']),
    equipment: j(['peso corporal', 'parede']),
    level: 'advanced',
    description: 'Desenvolvimento com o peso corporal em posição invertida.',
    techniqueTips: 'Use a parede como apoio; core e glúteos contraídos; desça a cabeça até o chão.',
    contraindications: j(['lesão no ombro', 'hipertensão não controlada']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'L-sit',
    muscleGroup: j(['core', 'reto abdominal', 'tríceps', 'iliopsoas']),
    modality: j(['ginástica', 'força']),
    equipment: j(['paralelas', 'peso corporal']),
    level: 'advanced',
    description: 'Posição isométrica de ginástica com corpo em "L".',
    techniqueTips:
      'Braços estendidos; pernas paralelas ao chão; progresso: joelhos dobrados → joelhos estendidos.',
    contraindications: j(['lesão no ombro', 'lesão no punho']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Bear crawl',
    muscleGroup: j(['core', 'ombros', 'quadríceps', 'corpo inteiro']),
    modality: j(['funcional', 'condicionamento']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description:
      'Rastejamento em quatro apoios com joelhos elevados — excelente para core e coordenação.',
    techniqueTips:
      'Joelhos a 2–3 cm do chão; movimentos opostos (mão direita + pé esquerdo); costas retas.',
    contraindications: j(['lesão no punho', 'lesão no ombro']),
    source: 'curated',
    isPublic: true,
  },
  {
    name: 'Inchworm',
    muscleGroup: j(['isquiotibiais', 'ombros', 'core']),
    modality: j(['mobilidade', 'funcional', 'aquecimento']),
    equipment: j(['peso corporal']),
    level: 'beginner',
    description: 'Mobilidade dinâmica que alonga isquiotibiais e ativa o core.',
    techniqueTips:
      'Pernas estendidas ao se curvar; caminhe com as mãos até flexão; opcional: adicione flexão no meio.',
    contraindications: j(['hérnia de disco']),
    source: 'curated',
    isPublic: true,
  },
]

async function seed() {
  console.log(`Populando biblioteca de exercícios (${LIBRARY.length} exercícios)...`)

  // Insere em lotes de 25 para não estourar o limite de parâmetros
  const BATCH = 25
  let inserted = 0

  for (let i = 0; i < LIBRARY.length; i += BATCH) {
    const batch = LIBRARY.slice(i, i + BATCH)
    await db.insert(exercises).values(batch).onConflictDoNothing()
    inserted += batch.length
    process.stdout.write(`  ${inserted}/${LIBRARY.length}\n`)
  }

  console.log(`\nSeed concluído — ${inserted} exercícios inseridos.`)
  await client.end()
}

seed().catch((err: unknown) => {
  process.stderr.write(`Seed falhou: ${String(err)}\n`)
  process.exit(1)
})
